### ISSUE TITLE
Handle missing labels

### ISSUE THREAD

**Issue by davkovacs** [ACEsuit/mace#1]
If there are no energy or forces keys defined it should fail by saying missing keys. 

Eventually we should implement handling of missing keys as well.

**Comment by ilyes319** [comment]
The models should now be able to handle missing labels on specific config type since #22 and #26. @davkovacs @bernstei How important is to support missing labels within the same config types. If it is important, how is it handled in GAP? It would be a per config weighting.

**Comment by bernstei** [comment]
What do you mean by missing "labels"?  Missing quantities like energy/forces/virial ?

**Comment by ilyes319** [comment]
Yes exactly.

**Comment by bernstei** [comment]
Per-config weights are supported, and that's how missing data is handled. In GAP I believe that the design matrix construction is not batched, so for every config rows are either added or not depending on what quantities are available.

Per-config weights are done in `config_from_atoms()` in https://github.com/ACEsuit/mace/blob/develop/mace/data/utils.py.  For example [line 133](https://github.com/ACEsuit/mace/blob/develop/mace/data/utils.py#L133) reads a weight from `Atoms.info["config_energy_weight"]`, or sets the weight to 0 if the energy is missing in [line 139](https://github.com/ACEsuit/mace/blob/develop/mace/data/utils.py#L139)

**Comment by ilyes319** [comment]
Perfect, so I think we need to add that to the readme, and close this issue.
