### ISSUE TITLE
Change name of swa to loss schedule

### ISSUE THREAD

**Issue by ilyes319** [ACEsuit/mace#104]
**Is your feature request related to a problem? Please describe.**
The current name of the loss scheduler (swa) is confusing.

**Describe the solution you'd like**
Change all occurence of it to a proper name. We first need to invent an alias that is both non confusing and usable. Ideas @gabor1 @davkovacs ?

**Describe alternatives you've considered**
None

**Additional context**
@gabor1 request

**Comment by davkovacs** [comment]
How about `phase_2_energy_weight`, `phase_2_forces_weight`, `phase_2_lr`, `start_phase_2` ?
