### ISSUE TITLE
Addition of trained model checkpoint files (or torchscript) to the repo

### ISSUE THREAD

**Issue by kryczko** [ACEsuit/mace#109]
It is much easier to benchmark different models if either the checkpoint files or a torchscript file is added to the repo. This could be easily integrated into your ASE calculators as well.

**Comment by ilyes319** [comment]
Hey, thank you for your issue. 
Could you make the problem more precise? After training, the model is saved as .model in your folder, and you can easily load it in the ASE caclulator afterwards (see [the calculator documentation.](https://mace-docs.readthedocs.io/en/latest/guide/ase.html))

**Comment by kryczko** [comment]
Sure, I can make my request more precise. The models that we're used to produce the results in this paper: https://arxiv.org/pdf/2305.14247.pdf. Could the checkpoints for them be uploaded here and used in the following way:
```
from mace.models import MaceOrganic

model = MaceOrganic() # reads in checkpoint file
calc = model.ase() # convert to ASE calculator

energy = calc.potential_energy()
```

An example of this can be seen in torchani: https://aiqm.github.io/torchani/api.html#module-torchani.models

This would make it very easy for me to do my own benchmarking. 

I hope this is more clear.

**Comment by davkovacs** [comment]
Checkpoints are here, we have uploaded them:
https://mace-docs.readthedocs.io/en/latest/examples/training_examples.html#ani-1x-dataset-h-c-n-o-transferable-ff
And the ASE calculator example is here:
https://mace-docs.readthedocs.io/en/latest/guide/ase.html

**Comment by kryczko** [comment]
Cool thanks, is this the correct link: https://github.com/ACEsuit/mace/blob/docs/docs/examples/ANI_trained_MACE.zip? 

It still would be easier if these files were just stored on github and we could just define a class rather than downloading a zip and loading those files into a class.
