### ISSUE TITLE
make the training code importable

### ISSUE THREAD

**Issue by stenczelt** [ACEsuit/mace#112]
**Is your feature request related to a problem? Please describe.**
I would like to embed MACE training into Python logic I am working on, though the training code cannot be readily installed and imported but is shown to be used through running a script.

**Describe the solution you'd like**
Simply refactor the `main()` function of the `run_train.py` script into the library itself, import it from there in `run_train.py` and allow packages to use MACE as a dependency for training as a result.

**Describe alternatives you've considered**
Calling the training code through subprocess. This is possible, but not ideal in my case.

**Comment by ilyes319** [comment]
I guess this now is possible in the dev branch, using the mace/cli/run_train.py . Please tell me if it works for you @stenczelt
