### ISSUE TITLE
Error Running LAMMPs on compiled variant

### ISSUE THREAD

**Issue by santi921** [ACEsuit/mace#125]
Hi! I was able to train a model successfully, serialize it, and compile the lammps variant that has the mace pair style. The problem I run into is whenever I even try to use the lmp command (with or without kokkos) I get the following error: 

`lmp: symbol lookup error: /data/santiago/lammps-mace/build/lmp: undefined symbol: _ZTIN3fmt6v9_lmp12format_errorE`

I attached the cmake command, environment, and cmake output from compiling the patched LAMMPS variant. 

- gcc/g++ version 11.3
- Cuda12.1
- GPU: A5000
[cmake.txt](https://github.com/ACEsuit/mace/files/11898598/cmake.txt)
[cmake_out.txt](https://github.com/ACEsuit/mace/files/11898599/cmake_out.txt)
[env.txt](https://github.com/ACEsuit/mace/files/11898600/env.txt)

**Comment by ilyes319** [comment]
Hey @santi921, thank you for your issue.
What branch are you using?

@wcwitt Do you have any idea where this could come from?

**Comment by wcwitt** [comment]
Thanks for reporting. We don't have much experience on other machines yet, so there are bound to be some growing pains.

Just to be clear - when you say it fails without Kokkos too, do you mean with Kokkos installed but not activated? Or with a non-Kokkos build?

**Comment by santi921** [comment]
I was able to compile it without kokkos as well to the same result

**Comment by santi921** [comment]
> Hey @santi921, thank you for your issue. What branch are you using?
> 
> @wcwitt Do you have any idea where this could come from?

I have predominantly tested on the multi-gpu branch but I was also getting this issue on the non-kokkos main branch.

**Comment by wcwitt** [comment]
@ilyes319, I would normally use `develop` (at least that's what our docs say at the moment) ... do you think the multi-gpu branch has everything that is needed? I'm guessing `main` is insufficient, unless there's been a merge recently.

**Comment by wcwitt** [comment]
Hi @santi921 - wondering if there's been any progress here, or if we should close?
