### ISSUE TITLE
installation instructions do not work out of the box

### ISSUE THREAD

**Issue by gabor1** [ACEsuit/mace#128]
**Describe the bug**

typing command from installation instructions results in error

**To Reproduce**
1. type "git clone git@github.com:ACEsuit/mace.git"
2. See error

```
gabor@Gabors-MacBook-Pro Downloads % git clone git@github.com:ACEsuit/mace.git
Cloning into 'mace'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
gabor@Gabors-MacBook-Pro Downloads % 
```

**Expected behavior**

mace to be cloned by git

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura

**Comment by ilyes319** [comment]
Closed, see #129
