### ISSUE TITLE
Lammps with GPU acceleration not working

### ISSUE THREAD

**Issue by Leimeroth** [ACEsuit/mace#138]
**Describe the bug**
Running a lammps simulation with a potential fitted for testing fails with following error when trying to run GPU accelerated version:

[W parser.cpp:3777] Warning: operator() sees varying value in profiling, ignoring and this should be handled by GUARD logic (function operator())
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [10,0,0], thread: [96,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed. (Line occurs multiple times)
cudaStreamSynchronize(stream) error( cudaErrorAssert): device-side assert triggered lammps_mace/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:172

I tried to compile lammps with mace and mace-dev branches and on a cluster and local machine. When running the CPU version it worked fine.

**To Reproduce**
Exemplary cmake command (Tried a few and had to adjust for different machines):

cmake -C ../lammps/cmake/presets/kokkos-cuda.cmake -C ../lammps/cmake/presets/gcc.cmake  -D CMAKE_BUILD_TYPE=Release -D BUILD_MPI=yes -D Kokkos_ARCH_PASCAL60=no -D BUILD_OMP=no -D BUILD_SHARED_LIBS=yes -D LAMMPS_EXCEPTIONS=yes -D Kokkos_ARCH_ZEN2=yes -D Kokkos_ARCH_AMPERE80=yes  -D Kokkos_ENABLE_OPENMP=no -D Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=no -D Kokkos_ENABLE_CUDA_UVM=no  -D PKG_ML-MACE=yes -D CMAKE_PREFIX_PATH=/work/groups/da_mm/apps/lammps_mace/libtorch-gpu -D CMAKE_CXX_STANDARD=17  ../lammps/cmake/

**Comment by wcwitt** [comment]
Hi @Leimeroth, apologies but I'm seeing this issue for the first time. Have you made any progress?

**Comment by Leimeroth** [comment]
After updating the mace and lammps versions, reinstalling everything from scratch and rewriting all input files it works now. I am not really sure what caused the problem.

**Comment by wcwitt** [comment]
Great, thanks, I will close.
