### ISSUE TITLE
error while doing forward simulation on cpu (model was trained on gpu)

### ISSUE THREAD

**Issue by utkarshp1161** [ACEsuit/mace#158]
Hi I am trying to run the md simulation using trained potential. I am passing device as CPU and have made sure that data is also on same device i.e CPU. Still I am getting the error described below.

Below is a snapshot of my code:

from ase import units
from ase.md.langevin import Langevin
from ase.io import read, write
import numpy as np
import time
import torch
import sys
import argparse
from mace.calculators import MACECalculator
from tqdm import tqdm
torch.set_default_dtype(torch.float64)
import time

def main(args):
    start_time=time.time()
    
    calculator = MACECalculator(model_path=args.model_path, device=args.device, default_dtype='float64')
    calculator.model.double() 
    model_name = "botnet"
    
    
    for i in tqdm(range(args.init_conf_N)):
        init_conf = read(args.init_conf_path, str(i))
        init_conf.set_calculator(calculator)
        dyn = Langevin(init_conf, args.timestep*units.fs, temperature_K=args.temp, friction=5e-3) 
        def write_frame():
            dyn.atoms.write(args.out_dir + f'md_{model_name}_langevin{i}.xyz', append=True)
        dyn.attach(write_frame, interval=1)
        dyn.run(args.runsteps)
        print(f"MD finished!{i}")
    running_time_seconds = time.time() - start_time
    print("Time taken: "+str(running_time_seconds/60) +" minute ")
            
        

error:

Traceback of TorchScript, original code (most recent call last):
  File "<eval_with_key>.157", line 83, in forward
    _w3j_1_2_1 = self._w3j_1_2_1
    mul_29 = _w3j_1_2_1 * 1.7320508075688772;  _w3j_1_2_1 = None
    tensordot = torch.functional.tensordot(einsum_13, mul_29, ([3, 4], [0, 1]), out = None);  mul_29 = None
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    einsum_14 = torch.functional.einsum('dbca,dbc->dba', tensordot, reshape_24);  tensordot = reshape_24 = None
    reshape_25 = einsum_14.reshape(getitem_4, 48);  einsum_14 = None
  File "/home/sire/phd/srz208500/anaconda3/envs/macex/lib/python3.9/site-packages/torch/functional.py", line 1100, in tensordot

 

    if out is None:
        return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
               ~~~~~~~~~~~~~ <--- HERE
    else:
        return _VF.tensordot(a, b, dims_a, dims_b, out=out)  # type: ignore[attr-defined]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

**Comment by utkarshp1161** [comment]
P.S It runs fine on GPU though.

**Comment by davkovacs** [comment]
Which branch and model were you using?

**Comment by Vaibhav525** [comment]
This error occurs in v0.2.0

**Comment by davkovacs** [comment]
Can you please try:

```py
import torch
model = torch.load("path", device="cuda")
model = model.cpu()
model = torch.save(model, 'cpu_hydrogen.model')
```

And run the newly saved model on CPU?

**Comment by Vaibhav525** [comment]
Thanks!. Works now.
