### ISSUE TITLE
entry points for scripts

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#177]
Would people be interested in adding entry points for some/all of the scripts, so they can become executables in the normal path when mace is pip installed?  If so, I'd be happy to have a go at it.  I'm hoping it's as simple as a few lines added to `setup.cfg`. There's a contribution of a mace fit wrapper to `wfl`, and it's easiest if we can count on `run_train.py` to in the path.

**Comment by gabor1** [comment]
sounds good to me.

**Comment by bernstei** [comment]
If it's going to be in the main path, should I added "mace_" as a prefix to each script name?

**Comment by ilyes319** [comment]
That would be nice. I don't know how this interacts with @stenczelt PR #113?

**Comment by bernstei** [comment]
> That would be nice. I don't know how this interacts with @stenczelt PR #113?

as long as `run_train.py` (and the other things in `scripts/`) exists, I don't think it'll matter.

**Comment by bernstei** [comment]
Should I branch from main or develop?

**Comment by bernstei** [comment]
Are all the python scripts worth exposing?
```scripts/active_learning_md.py
scripts/create_lammps_model.py
scripts/eval_configs.py
scripts/plot_train.py
scripts/run_train.py
```

**Comment by ilyes319** [comment]
yes I think so, the multi-gpu and high-perf will add one or two scripts that can add later.

**Comment by stenczelt** [comment]
Yeah agreed. The scripts can have entry points and still be thin wrappers around importable functions etc.

**Comment by bernstei** [comment]
> > That would be nice. I don't know how this interacts with @stenczelt PR #113?
> 
> as long as `run_train.py` (and the other things in `scripts/`) exists, I don't think it'll matter.

I guess there is a chance for a conflict, depending on what exactly #113 is changing. The conflict resolution should be easy, though. As long as the final "executable" has a `main()` function, it'll just need to be moved to `mace/cli/`, and if it's no longer called `run_train.py` the entrypoint in `setup.cfg` will have to be updated.

You OK, with that, @stenczelt ?

**Comment by ilyes319** [comment]
Hopefully we can close that if @stenczelt is happy also

**Comment by stenczelt** [comment]
yeah, happy. Feel free to close this one.
