### ISSUE TITLE
Adding pretrained universal MACE on Huggingface

### ISSUE THREAD

**Issue by chiang-yuan** [ACEsuit/mace#187]
I have been working with @janosh and collaborators on [Matbench Discovery](https://matbench-discovery.materialsproject.org/) and trained a couple of universal mace checkpoints (for 89 elements trained on [MPTrj](https://figshare.com/articles/dataset/23713842), relaxation trajectories on Materials Project). Janosh has put one of them used for matbench discovery dashboard and [preprint](https://matbench-discovery.materialsproject.org/preprint) publicly available on [github](https://github.com/janosh/matbench-discovery/tree/main/models/mace). I thought this would be of interest to broader audience, so I put the the pretrained checkpoints on huggingface [here](https://huggingface.co/cyrusyc/mace-universal). 

Ping @ilyes319

**Comment by ilyes319** [comment]
Hey @chiang-yuan and @janosh, thank you for the very nice work. Happy for it to be on huggingface, we can also have a link to the model and the paper in the mace documentation if you are ok with that.
