### ISSUE TITLE
LAMMPS-MD-MACE error

### ISSUE THREAD

**Issue by bjn123** [ACEsuit/mace#194]
While using the MACE model in the LAMMPS MD simulation, I got the following error.  Please note that, I am using the CPU version 

CUDA unavailable, setting device type to torch::kCPU.
Loading MACE model from "[sodium-t568_run-123_epoch-192_swa.pt](http://sodium-t568_run-123_epoch-192_swa.pt/)" ...Exception: PytorchStreamReader failed locating file constants.pkl: file not found

Exception raised from valid at ../caffe2/serialize/inline_container.cc:178 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f769d39cd77 in /opt/lammps-mace-cpu/libtorch/lib/libc10.so)
...
How to fix it.

**Comment by wcwitt** [comment]
Hi - thanks for the interest in MACE-LAMMPS. Could you please provide some more information (e.g., versions of pytorch, libtorch, etc., as well as your input script).

**Comment by bjn123** [comment]
I have tried both versions of pytorch 1.3.0-cpu and 2.0.0-cpu with LAMMPS (28 Mar 2023). The input file is attached for your reference.
[nvt.zip](https://github.com/ACEsuit/mace/files/13015099/nvt.zip)

**Comment by bjn123** [comment]
Thank you sir for your reply. I have reinstalled the Lammps package as mentioned in the above link. In the mace/scripts directory, there is no such script namely "create_lammps_model.py". Therefore I am unable to execute the following command as mentioned in documentation.
"python [mace_dir]/scripts/create_lammps_model.py my_mace.model"

**Comment by wcwitt** [comment]
Note that the instructions say to use the `develop` branch. If you do that, you'll find the script as advertised.

For example: https://github.com/ACEsuit/mace/tree/develop/scripts.

Eventually, this script will also appear in `main`.

**Comment by bjn123** [comment]
Thank you sir. LAMMPS MD is working now
