### ISSUE TITLE
isolated_atom_config search logic is broken

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#197]
The logic that searches for `isolated_atom_config` starting here
https://github.com/ACEsuit/mace/blob/76d588be5fa63f1b9ca7f96b69c89007376db621/mace/data/utils.py#L210 appears to be broken. If there's a single atom config that has a `config_type` set but it isn't `"IsolatedAtom"` the `isolated_atom_config` variable is undefined a couple lines below, where the code tries to use it.

**Comment by bernstei** [comment]
I think it'd be simpler to just do
```
isolated_atom_config = atoms.info.get("config_type") == "IsolatedAtom"
```
rather than messing around with an explicit exception handler.

**Comment by ilyes319** [comment]
Very nice catch, just changed it! Thank you
