### ISSUE TITLE
Add example descriptors for MP MACE

### ISSUE THREAD

**Issue by ilyes319** [ACEsuit/mace#199]
**Describe the feature**
Create an example in the documentation to use the material project model as descriptors. And make a default descriptor.

**Comment by ilyes319** [comment]
@gabor1 Currently, the descriptors are attached to calculators and not stand alone. Should we make an exception for foundation models, where we provide a script that provides out of the box calculator basically? So one could do, `from mace.foundations import macemp` or `from mace.foundations import maceoff` ? And that would provide an ase calculator of the corresponding model?

**Comment by gabor1** [comment]
I think it would be nice to ut in place multiple paths. for people who don't want to think about the potential energy at all, it's nice to be able to compute descriptors independently. for those who are working with the model as a potential energy calculator, it's also good to be able to access the descriptors separately. I hope I understood the issue..
