### ISSUE TITLE
Torchscript support and OpenMM and LAMMPS

### ISSUE THREAD

**Issue by ilyes319** [ACEsuit/mace#2]
Being able to compile MACE models is of high priority :

- [X] Compile with torchscript the internal functionalities of MACE.
- [X] Write test for compiled modules.
- [X] Resolve incompatibilities between torchscript and AtomicData.
- [X] Compile the full model with torchscript.
- [X] Create deployed model with metadata (r_cut, species).
- [x] Load model in C++ using libtorch.
- [x]  Compiled version of neighboring list.
- [x] Create interface to OpenMM.
- [x] Create interface to LAMMPs with pair potential.

**Comment by davkovacs** [comment]
The OpenMM is currently tested here:
https://github.com/davkovacs/mace/tree/openmm3

**Comment by ilyes319** [comment]
In order to merge that we need to add in the readme:

- [ ] A presentation of the new functionalities (one for openMM, one for lammps) 
- [ ] How to use them with link to the associated repos and their installation guides
- [ ] A notebook example would be awesome

 @davkovacs  @wcwitt @jharrymoore Anything more?

**Comment by wcwitt** [comment]
Should we also add the ability to create a LAMMPs potential directly from `run_train`? The procedure right now requires an extra script.

**Comment by nickhine** [comment]
Is this ready to try? I'd be keen to see an example.

**Comment by davkovacs** [comment]
@nickhine which one would you like to try? OpenMM or LAMMPS? 
OpenMM works for non-periodic simulations only at the moment, but we are working on it actively to enable periodic / bulk simulations. LAMMPS works on CPU-s, and the GPU implementation is ongoing.

**Comment by nickhine** [comment]
I was interested in the LAMMPS version, applied to a periodic system - particularly if the performance for small/medium sized systems is respectable on CPU.

**Comment by wcwitt** [comment]
Hi @nickhine, can you email me at wcw28@cam.ac.uk? I'll send you an example and can help with any problems.

**Comment by hityingph** [comment]
Hi @wcwitt, I recently utilized MACE in my project (using a cutoff of 7 angstrom and 2 layers for bilayer graphene with defects) and was impressed with its high accuracy (energy RMSE =0.3 meV/atom, force RMSE = 20 meV/A). However, I noticed that the LAMMPS interface only supports CPU without MPI, resulting in a limited speed of 30 atom-steps/second for a 1000-atom system with 48 cores. I have followed the introductions in the mannual to perform the MD simulations. May I kindly inquire if there is a GPU implementation available now, as I would be very interested in trying it out? Otherwise, do you have any suggestions on improviding the runing speed for MD simulations?

**Comment by wcwitt** [comment]
Hi @hityingph,

Glad you are finding MACE useful, and thanks for the interest in the LAMMPS interface!

> only supports CPU without MPI

This is not strictly true, but I agree that for 1000 atoms you are unlikely (at present) to get much speedup from MPI parallelization.

> May I kindly inquire if there is a GPU implementation available now

We do have a LAMMPS GPU version, but we are still testing it internally. You can expect a public version very soon - I'd suggest waiting for that, unfortunately.

**Comment by ilyes319** [comment]
Hi @hityingph, 

Thank you for using MACE!

While waiting for the GPU interface for LAMMPs you might be able to run some faster MD with openMM (see https://mace-docs.readthedocs.io/en/latest/guide/openmm.html) that runs on GPU.

**Comment by hityingph** [comment]
@wcwitt  Thanks for your prompt response, and I look forward to the GPU version!

Hi @ilyes319 , thank you for recommending the OpenMM interface. I'm not familiar with OpenMM, and I'm curious if it has some features similar to those in LAMMPS that I need (such as the "fix spring" function I used for sliding simulations). Nevertheless, I will give it a try to get a general understanding of the running speed of MACE using a GPU.

**Comment by ilyes319** [comment]
I am closing this issue now as all this is officially supported. One can find details of these features in the User guide of the [documentation](https://mace-docs.readthedocs.io/en/latest/).
