### ISSUE TITLE
MACECalculator PyTorch RuntimeError

### ISSUE THREAD

**Issue by stefanbringuier** [ACEsuit/mace#200]
I encountered a type mismatch error while using trying to use the `MACECalculator` with `ASE`. Below is the code snippet along with the error message:

```python
from ase.spacegroup import crystal
from mace.calculators import MACECalculator

mace = MACECalculator(model_path='2023-08-14-mace-universal.model', device="cuda")

a = b = c = 2.8665
iron_bcc = crystal(["Fe","Fe"],
            [(0, 0, 0), (0.5, 0.5, 0.5)],
            spacegroup=229,
            cellpar=[a, b, c, 90, 90, 90],
            pbc=True)

iron_bcc.calc = mace
pe = iron_bcc.get_potential_energy()
```

The above code results in the following error:

```plaintext
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-caa6bdddc510> in <cell line: 12>()
     10 
     11 iron_bcc.calc = mace
---> 12 pe = iron_bcc.get_potential_energy()
     13 print(pe)

9 frames
/usr/local/lib/python3.10/dist-packages/mace/modules/blocks.py in forward(self, x)
    135         self, x: torch.Tensor  # one-hot of elements [..., n_elements]
    136     ) -> torch.Tensor:  # [..., ]
--> 137         return torch.matmul(x, self.atomic_energies)
    138 
    139     def __repr__(self):

RuntimeError: expected scalar type Double but found Float
```

#### Environment
Python version: 3.10.12
PyTorch version: 2.1.0+cu118
MACE version: 0.2.0

**Google Colab Setup**
```python
! pip3 install ase
! pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
! git clone https://github.com/ACEsuit/mace.git
! pip install ./mace
```

Thanks in advance

**Comment by ilyes319** [comment]
Hey @stefanbringuier , can you try to change your 3rd line to `mace = MACECalculator(model_path='2023-08-14-mace-universal.model', device="cuda", default_dtype="float64")`?

**Comment by stefanbringuier** [comment]
Added the kwarg `default_dtype="float64"` but still the same error: `RuntimeError: expected scalar type Double but found Float` in `blocks.py` 

However, this call works on **Google Colab (T4 GPU)**:

```python
mace = MACECalculator(model_path="2023-08-14-mace-universal.model",
                      device="cpu",
                      default_dtype="float32")
```

but this does not:

```python
mace = MACECalculator(model_path="2023-08-14-mace-universal.model",
                      device="cuda",
                      default_dtype="float32")
```

and gives a different error:

```
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:
...
...
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
```

Unfortunately, I can't test using a GPU locally since I don't have a suitable card.


My guess is for small atomic systems (i.e. < 100 atoms) the force and energy calculations will be "quick" enough on the cpu to use but probably not so for large systems.

**Comment by mhellstr** [comment]
I get the exact same errors on my local machine when trying to use the 2023-08-14-mace-universal.model, using Python 3.8 and pytorch 1.13.1+cu117.

default_dtype="float32" gives some results on the CPU but fails on the GPU.
Skipping default_dtype fails both on CPU and GPU.

**Comment by ilyes319** [comment]
Why would you like to use `device="cuda:0"` instead of `device="cuda`

**Comment by mhellstr** [comment]
With multiple GPUs I may want to control on which device to run. I believe ``device="cuda"`` is just a synonym for ``device="cuda:0"``, although I'm not exactly sure.

```
>>> torch.tensor([1,2,3], device="cuda")
tensor([1, 2, 3], device='cuda:0')
>>> torch.tensor([1,2,3], device="cuda:0")
tensor([1, 2, 3], device='cuda:0')
```

**Comment by ilyes319** [comment]
We merged a PR for that, it should work now
