### ISSUE TITLE
Lammps calculation error

### ISSUE THREAD

**Issue by hwsheng** [ACEsuit/mace#205]
Hi all, I was able to use the create_lammps_model.py script (found in the ..//mace/cli/ directory from the develop branch) to prepare a torchscript-compiled lammps_mace model. I assume this is still the script to create a lammps-enabled trouchscript 

For a test run using cpus, I received the following error: 

`Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.001
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/mace/calculators/lammps_mace.py", line 45, in forward
        _6 = torch.ones_like(total_energy_ghost)
        grad_outputs = annotate(List[Optional[Tensor]], [_6])
        _7 = torch.autograd.grad([total_energy_ghost], [displacement1], grad_outputs, True, True, True)
             ~~~~~~~~~~~~~~~~~~~ <--- HERE
        virials1 = _7[0]
        if torch.__isnot__(virials1, None):`

`Traceback of TorchScript, original code (most recent call last):
  File "/home/hsheng/research/mace-venv/lib/python3.8/site-packages/mace/calculators/lammps_mace.py", line 55, in forward
                torch.ones_like(total_energy_ghost)
            ]
            virials = torch.autograd.grad(
                      ~~~~~~~~~~~~~~~~~~~ <--- HERE
                outputs=[total_energy_ghost],
                inputs=[displacement],
RuntimeError: One of the differentiated Tensors does not require grad`

`

The following is my training file: 
`python /home/hsheng/research/mace/scripts/run_train.py \
    --name="TiZrHfCu" \
    --train_file="train.xyz" \
    --valid_fraction=0.05 \
    --test_file="test.xyz" \
    --model="MACE" \
    --E0s="average" \
    --num_interactions=2 \
    --num_channels=64 \
    --max_L=2 \
    --correlation=3 \
    --r_max=6.0 \
    --compute_stress=true \
    --forces_weight=1000 \
    --energy_weight=10 \
    --energy_key="energy" \
    --forces_key="forces" \
    --virials_key="virial" \
    --loss=virials \
    --batch_size=5 \
    --valid_batch_size=4 \
    --max_num_epochs=800 \
    --start_swa=400 \
    --scheduler_patience=15 \
    --patience=30 \
    --eval_interval=4 \
    --ema \
    --swa \
    --error_table='PerAtomMAE' \
    --default_dtype="float32"\
    --device=cuda \
    --seed=123 \
    --restart_latest \
    --save_cpu \
`

Any suggestions on how to proceed with this?

**Comment by wcwitt** [comment]
Can you send your LAMMPS input please?

**Comment by hwsheng** [comment]
Here is my lammps input file. 

`units           metal
boundary        p p p

atom_style      atomic
atom_modify map yes
newton on

read_data       data_mace

mass    1 47.8
mass    2 91.22
mass    3 63.54
mass    4 178.49

pair_style mace no_domain_decomposition
pair_coeff * * ../TiZrHfCu_swa.model-lammps.pt Ti Zr Cu Hf


velocity all create 323 4928459 rot yes dist gaussian

fix             1 all nvt temp 323 2323 0.2
thermo          100
timestep        0.001
dump            dump all custom 10000 dump.dat id type xu yu zu
run             200000`

**Comment by hwsheng** [comment]
FYI, I was able to use the MACEcalculator in ASE to run MD.

**Comment by wcwitt** [comment]
Okay after looking more closely at this trace:

> Traceback of TorchScript, original code (most recent call last): File "/home/hsheng/research/mace-venv/lib/python3.8/site-packages/mace/calculators/lammps_mace.py", line 55, in forward torch.ones_like(total_energy_ghost) ] virials = torch.autograd.grad( ~~~~~~~~~~~~~~~~~~~ <--- HERE outputs=[total_energy_ghost], inputs=[displacement], RuntimeError: One of the differentiated Tensors does not require grad

it's clear that this model was trained using `main`, not `develop`. Note that the [docs](https://mace-docs.readthedocs.io/en/latest/guide/lammps.html) say (for now): "Train the model using the develop branch". I'm pretty sure that's the problem.

**Comment by hwsheng** [comment]
Yes, you are right. After training the model using `develop`, the deployed mace model works fine in lammps. Many thanks.

**Comment by wcwitt** [comment]
Great, seems this is resolved.
