### ISSUE TITLE
Location for LAMMPS script

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/mace#210]
Hi @ilyes319 @bernstei, I just realized the `create_lammps_model.py` script was moved to `/mace/cli`/. Was that intentional? If so, I just need to update the LAMMPS instructions. Relates to #203.

**Comment by wcwitt** [comment]
Ah, I've just seen #198. Thanks. We can close when #198 is merged.

**Comment by ilyes319** [comment]
ok it is merged, sorry for the delay. We can close it now.
