### ISSUE TITLE
overly restrictive data file suffix requirements

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#23]
Is there a particular reason why `load_from_xyz()` restricts the file suffix to `".xyz"` and passes a format explicitly, rather than just letting ASE do what it can when reading? This breaks files that are named `".extxyz"`, which `ase.io.read()` handles without a problem.

**Comment by ilyes319** [comment]
We definitly should add an assert including other extensions.  What other extensions can it support?

**Comment by bernstei** [comment]
Tens of them, but not all support quantities such as energies/forces/etc.  And anyway, why an assert?  Why not let it raise an exception if it can't handle it?

**Comment by bernstei** [comment]
https://wiki.fysik.dtu.dk/ase/ase/io/io.html

**Comment by davkovacs** [comment]
You are completely right. This should be much better handled.

**Comment by davkovacs** [comment]
I can fix this.

**Comment by davkovacs** [comment]
https://github.com/ACEsuit/mace/commit/d569918828465361fa0e07f089f9f25b070eab32

**Comment by davkovacs** [comment]
I will close this when you say the fix is okay.

**Comment by bernstei** [comment]
I put in some comments on the commit.

**Comment by davkovacs** [comment]
Can I close this issue?

**Comment by bernstei** [comment]
Fine by me, yes.

**Comment by ilyes319** [comment]
Closing, looks fine.
