### ISSUE TITLE
Publish MACE on PyPI

### ISSUE THREAD

**Issue by janosh** [ACEsuit/mace#258]
Just to leave a public record, as discussed on Dec 6 over Slack, MACE should become a PyPI package for easy distribution and versioning. There are no imminent plans but I think it would be great to get it done this year.

**Comment by ilyes319** [comment]
I am on ir

**Comment by Andrew-S-Rosen** [comment]
Thank you, @ilyes319!!!

**Comment by Andrew-S-Rosen** [comment]
Hi @ilyes319: Any update on this? Also, do we need to strictly pin the version of `e3nn`?

**Comment by ilyes319** [comment]
Updates are coming soon.

**Comment by ilyes319** [comment]
Closing this as done now.
