### ISSUE TITLE
Incorrect dimensions on the stress property in the ASE calculator

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [ACEsuit/mace#259]
**Describe the bug**
The `stress` calculator property is a flat array rather than a matrix, the latter of which is standard across ASE calculators.

**To Reproduce**

```python
from mace.calculators import mace_mp
from ase.build import bulk

atoms = bulk("Cu") * (2,2,2)
atoms.calc = mace_mp()
atoms.get_potential_energy()
print(atoms.calc.results["stress"])
```

**Expected behavior**
A multi-dimensional matrix should be returned, not a flat array of length 6.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] commit 2cc2f64

**Additional context**
For reference, the stress dimensions are correct in M3GNet and CHGNet if you want to take a look.

**Comment by gabor1** [comment]
Is it in Voigt notation, also standard in ASE? There are convenience functions to convert.

**Comment by ilyes319** [comment]
The Voigt notation is the default in ASE. 

(https://wiki.fysik.dtu.dk/ase/ase/atoms.html#ase.Atoms.get_stress)
Calculate stress tensor.

Returns an array of the six independent components of the symmetric stress tensor, in the traditional Voigt order (xx, yy, zz, yz, xz, xy) or as a 3x3 matrix. Default is Voigt order.

**Comment by Andrew-S-Rosen** [comment]
Ah, thanks! I was trying to sort out why M3GNet and CHGNet were giving different dimensions than MACE --- looks like both are accepted, my mistake. I wasn't familiar with the Voigt ordering before. Should have seen that in the docs.
