### ISSUE TITLE
units in dataset of liquid water example

### ISSUE THREAD

**Issue by uccasco** [ACEsuit/mace#262]
**Describe the bug**
The dataset described in the liquid [water example](https://mace-docs.readthedocs.io/en/latest/examples/training_examples.html#liquid-water) uses atomic units. It might be worth mentioning this, as MACE uses eV, Angstrom etc. Presumably the dataset needs converting, or there is a keyword that deals with this (in which case, please describe).

I have a script that does the conversion if that would be helpful.

**Comment by davkovacs** [comment]
Yes, you are right, that dataset has to be processed before fitting, which means unit conversion primarily. MACE only works with eV / A.
