### ISSUE TITLE
Possibility to not compute energies on `MACE.forward`

### ISSUE THREAD

**Issue by pfebrer** [ACEsuit/mace#338]
**Is your feature request related to a problem? Please describe.**
I'm trying to think about how to use the main MACE model to train on things other than energies (i.e. having a custom readout) without having to rewrite the whole model.

**Describe the solution you'd like**
I think having a `compute_energies` argument on `MACE.forward` that defaults to `True` could be great. Then one could set it to `False` and use the main mace model to just get node features and then do whatever you want with them. It would also be straightforward to take a model that is pretrained for energies and then start training it for something else. This argument would be minimally invasive and would not introduce any problems in terms of compatibility (I think).

**Describe alternatives you've considered**
- Rewriting the model's code on my library using a different readout. This is not good since we need to make sure that the code is up to date with the latest MACE in this repo.
- Using mace layers. This is a better option but still you need to implement the interactions loop, and it doesn't make it straightforward to reuse some pretrained weights from MACE.
- Make MACE accept a readout function. I think this would not be as customizable and would complicate things inside MACE. 
- Just let it compute energies and not use them. Probably not too bad, but it would compute things unnecessarily.

**Comment by ilyes319** [comment]
Hey,

MACE already returns the node features, so you can easily use it this way already. The computation of the energy adds very little cost, so that will not be a problem.

**Comment by pfebrer** [comment]
Hi, I'm trying to use in the way you propose it, but MACE hardcodes the last hidden irreps to be only scalars:

https://github.com/ACEsuit/mace/blob/2d89108d4ec27ada6ae7e63b70f79c63ed1007e7/mace/modules/models.py#L137-L140

Could there be a way of tweaking this from the inputs of MACE?

To clarify, what I would want is that the last node features could be of the same shape that the node features for the rest of interactions :sweat_smile:
