### ISSUE TITLE
questions about mace documentation

### ISSUE THREAD

**Issue by 1234zou** [ACEsuit/mace#347]
Dear MACE developers,

Thank you for developing the wonderful MACE. I'm new to MACE and thus my questions may be naive. I've successfully installed MACE and running examples [here](https://github.com/ilyes319/mace-tutorials/blob/main/mace-users/MACE_users.ipynb). When I look into the OpenMM interface documentation, I encounter several problems:

(1) For `mamba env create -f mace-openmm.yml`, can you show an example about what is in the file mace-openmm.yml? Is it something like `torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2`?

(2) For `pip install git+https://github.com/jharrymoore/openmm-ml.git@mace`, I encounter the error
```
INFO: pip is looking at multiple versions of openmmml to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement openmm>=7.5 (from openmmml) (from versions: 0.1, 0.2)
ERROR: No matching distribution found for openmm>=7.5
```
It seems this is a compatibility problem between openmm and opemm-ml.

(3) Can I install the master branch of `openmm-ml` and `openmmtools`? Or I have to install the branch in `https://github.com/jharrymoore/`?

Your kind help would be greatly appreciated.

**Comment by jharrymoore** [comment]
Could you try building the conda environment from [this file](https://github.com/jharrymoore/openmmtools/blob/development/mace-openmm.yml)? Then you should be able to run the `pip install` commands from the docs. 

You need our forks of both openmmtools and openmm-torch to be compatible with MACE

**Comment by 1234zou** [comment]
Thanks, @jharrymoore . It works with the file `mace-openmm.yml`. However, `torchvision` and `torchaudio` is not included in this .yml file. If I install them via `pip install`, `pytorch-2.0.1` will be downloaded and installed. But `pytorch-2.0.0` is already written in this .yml file. Would you please tell me how to install `torchvision` and `torchaudio` in such case?

By the way, there is a `sklearn` in the file `openmmtools/openmm_torch/repex.py`,
```
from sklearn.random_projection import sample_without_replacement
```
But I look into this file and find `sample_without_replacement` is not used at all. So this line is supposed to be deleted. Otherwise it will lead to errors when I run `mace-md`.

**Comment by jharrymoore** [comment]
I don't believe we depend on torchvision or torch audio packages in mace or through mace-md. Do you need these in your environment for some other reason? 

On the unpicking error, this normally indicates your model did not download properly, could you inspect the downloaded file and check this looks like a model file (should be several MB in size)

**Comment by jharrymoore** [comment]
Great, can I confirm your installation works as expected now? Thank you for the comment on the docs - this command has been updated now

**Comment by skarlotte** [comment]
Hi! I am also trying to install MACE-MP-0 in an OpenMM environment on csd3's ampere node. By any chance, could you advise me if there are any differences in setting up the environment on csd3? Do I have to create an interactive node for that, or can I create the environment on the login-node?
