### ISSUE TITLE
How to add two MACE models in `mace-md`?

### ISSUE THREAD

**Issue by 1234zou** [ACEsuit/mace#351]
Dear MACE developers,

Would you please tell me how to use the sum/addition of two MACE models in `mace-md`? For example, assuming I use one model to fit the `B3LYP` functional, and another model to fit `D3(BJ)` dispersion correction, now I want to use the sum of their predicted energies and forces in the mace-openmm MD simulations.

Although I can write such a utility/script by myself, it would be great if MACE already has such functionality. Any example/tutorial would be greatly appreciated.

Thanks a lot!

**Comment by ilyes319** [comment]
The easiest approach would be to utilize the SumCalculator object within ASE. In the case of OpenMM, I would should do this manually, as we do not plan to offer support for it. The most straightforward method for you would be making the necessary corrections at the DFT level and then fitting directly on the output.
