### ISSUE TITLE
difference in scripts_utils.py between cloning via "git clone git@github.com" and "git clone https://github.com"

### ISSUE THREAD

**Issue by drsillybird** [ACEsuit/mace#374]
Dear all, 

I'm observing a version difference in $SOMEPATH/lib/python3.10/site-packages/mace/tools/scripts_utils.py 
between cloning via 
git clone git@github.com:ACEsuit/mace.git
and 
git clone https://github.com/ACEsuit/mace.git
after subsequent 
pip install ./mace

The files differ in size by 3000 bytes and show different behaviour (only the smaller one sourced via https works for training). 

ls -l  tmp/mace/tools/scripts_utils.py ~/.local/lib/python3.10/site-packages/mace/tools/scripts_utils.py
-rw-r----- 1 vsc43551 vsc43551 10564 Apr 11 08:56 ~/.local/lib/python3.10/site-packages/mace/tools/scripts_utils.py
-rw-r----- 1 vsc43551 vsc43551 13312 Apr 10 11:20 tmp/mace/tools/scripts_utils.py
(The latter was saved for comparison in some different location.)

I just wonder if I'm doing something stupid. My impression was, that with both git cloning commands I'll receive the main branch of mace.

Any suggestions are welcome.

Thanks a lot & best regards,

Alexander

**Comment by drsillybird** [comment]
Hello Ilyes, thanks for looking into it!

The one with the prefix 'doeswork' comes via the https source and does its job one one GPU.

Best regards, Alexander

[script_utils_from_mace.zip](https://github.com/ACEsuit/mace/files/14954953/script_utils_from_mace.zip)

**Comment by ilyes319** [comment]
Apparently when you are doing `git clone git@github.com:ACEsuit/mace.git`, it installs the develop branch. You might have things that are cached. What does not work with the other code?

**Comment by drsillybird** [comment]
Hello again, 

you are right, I can _not_ reproduce the error with a new installation. It seems there was confusion on my side during playing around with different code branches.

Sorry for troubling you. Thanks again!

Alexander
