### ISSUE TITLE
undefined calc in multi-head-finetune branch run_train.py

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#380]
In the `multi-head-finetune` branch, `mace/cli/run_train.py` line 432 
https://github.com/ACEsuit/mace/blob/f5ab9c5d45e09ac49c7874c44a14ba83c813d5ab/mace/cli/run_train.py#L432 refers to a variable `calc`, but there are many code paths (various nested ifs around https://github.com/ACEsuit/mace/blob/f5ab9c5d45e09ac49c7874c44a14ba83c813d5ab/mace/cli/run_train.py#L93) that don't define it

**Comment by ilyes319** [comment]
should be fine in develop.
