### ISSUE TITLE
dict_to_array (in multi-head-finetune) does not ensure E0s are in correct order

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#382]
The multi-head-finetune branch does not fix the order of the E0s in the situation where the E0s dict does not contain sub-dicts for each "theory"
https://github.com/ACEsuit/mace/blob/f552d6c89b5f19365706580c12d2dadf4a6a6ed4/mace/tools/scripts_utils.py#L231

Probably want something like
```
ordered_keys = sorted([int(k) for k in data.keys()])
return np.array([data[k] for k in ordered_keys])
```

**Comment by ilyes319** [comment]
closing this as it is fixed in develop.
