### ISSUE TITLE
Fine tuning pre-trained model

### ISSUE THREAD

**Issue by pdm9600** [ACEsuit/mace#384]
Hi all,

I'm trying to fine-tune the pre-trained model on mp data (as in https://github.com/ACEsuit/mace-mp).
I downloaded mace (v0.3.4) via pip install mace-torch.

I've looked at other related posts, and found that the pre-trained models are loaded with the "--foundation_model" option. However, I don't see this available when I run 'mace_run_train' or 'run_train.py'

Also, training from scratch works fine. 

Here's my output when I try to include the pre-trained models (similar output for mace_run_train as well):

> run_train.py: error: unrecognized arguments: --foundation_model=2024-01-07-mace-128-L2.model

**Comment by ilyes319** [comment]
Hello,

This functionality is only available in the develop branch for now. You need to install it in order to use it.
