### ISSUE TITLE
mace_run_train: unrecognized arguments: `--foundation_model` on pip installer version

### ISSUE THREAD

**Issue by stenczelt** [ACEsuit/mace#396]
**Describe the bug**
When installed from `pip` (as per readme) and trying to run fine-tuning of the foundation models, the associated argument of the `mace_run_train` is unrecognised.

**To Reproduce**
1. install from pip: https://github.com/acesuit/mace?tab=readme-ov-file#pip-installation
2. try fine-tuning foundation models: https://github.com/acesuit/mace?tab=readme-ov-file#finetuning-foundation-models

**Expected behavior**
I guess this just needs a release, I am currently on `mace-torch==0.3.4` which seems to be the latest from pypi, but released there in Jan 2024.

**Comment by ilyes319** [comment]
Yes fixing all bugs before releasing
