### ISSUE TITLE
How do you generate the input xyz files for MD22?

### ISSUE THREAD

**Issue by tkreiman** [ACEsuit/mace#406]
I am following the tutorial linked here (https://mace-docs.readthedocs.io/en/latest/examples/training_examples.html#md22-large-molecules). I was wondering how to generate / obtain the input xyz files from that tutorial. I tried using the xyz files from sgml.org, however, those don't include the forces.

Thanks for the help.

**Comment by ilyes319** [comment]
We obtained the input xyz from the same website http://www.sgdml.org/#datasets. When I download, they include the forces.
