### ISSUE TITLE
a couple of weird statements in new multihead fine-tuning interface code

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#408]
What is line line supposed to be doing?
https://github.com/ACEsuit/mace/blob/fb35950bea8d720c2dde923c9b4fbd153d6b92ab/mace/cli/run_train.py#L184

Why are these keys taken from the user's settings, rather than a default (plain?) property name, or just ignored?
https://github.com/ACEsuit/mace/blob/fb35950bea8d720c2dde923c9b4fbd153d6b92ab/mace/cli/run_train.py#L265

**Comment by ilyes319** [comment]
First statement is for removing duplicate heads, transforming ["pbe_mp", "pbe_mp", "r2scan"] to ["pbe_mp", "r2scan"].
Second line, we should remove.

**Comment by bernstei** [comment]
> First statement is for removing duplicate heads, transforming ["pbe_mp", "pbe_mp", "r2scan"] to ["pbe_mp", "r2scan"].

if we know that `heads` starts out as a list, `list(set(["pbe_mp"] + heads))` is cleaner in my opinion. But if we care about the order, I'm not sure what `set()` guarantees.  But also, if we care about the order, I think something more explicit is better anyway (e.g. `["pbe_mp"] + list(set(heads) - set(["pbe_mp"]))`.   What _exactly_ are the requirements of the result of this statement?

**Comment by ilyes319** [comment]
closing this as it is fixed in develop.
