### ISSUE TITLE
Error reading 'extended' xyz format files

### ISSUE THREAD

**Issue by venkatkapil24** [ACEsuit/mace#415]
**Describe the bug**
MACE returns error for an ".extxyz" file. 

Traceback (most recent call last):
  File "/home/ucapvka/source/mace/scripts/run_train.py", line 6, in <module>
    main()
  File "/lustre/home/ucapvka/mace-venv/lib/python3.9/site-packages/mace/cli/run_train.py", line 157, in main
    assert args.train_file.endswith(".xyz"), "Must specify atomic_numbers when using .h5 train_file input"
AssertionError: Must specify atomic_numbers when using .h5 train_file input

Typically XYZ files do not include anything other than positions/velovities. On the other hand, the extended XYZ in ASE/libatoms '.extxyz' is the standard format. I think MACE should include it and not assume .h5. Again, happy to open a quick PR.

**Comment by ilyes319** [comment]
Hey @venkatkapil24, MACE can read extended xyz, but you need to rename the extension just `.xyz`.

**Comment by bernstei** [comment]
That's essentially a bug, I'd argue.  If anything, I'd say it should required ".extxyz"

**Comment by gabor1** [comment]
I agree it should accept both .xyz and .extxyz

**Comment by bernstei** [comment]
I'm not even convinced it should check anything except, I guess, special-casing `.h5`.  Anything else it could just pass to `ase.io.read` and let it deal with it automatically.

**Comment by venkatkapil24** [comment]
> I'm not even convinced it should check anything except, I guess, special-casing `.h5`. Anything else it could just pass to `ase.io.read` and let it deal with it automatically.

I agree. This will also help read directly from json.

**Comment by bernstei** [comment]
> I agree. This will also help read directly from json.

iff it's json that `ase.io.read` can parse

**Comment by stargolike** [comment]
today i upgrade my mace, and i meet this problem. it's not good idea, yesterday i can use extxyz and now i can't.

**Comment by ilyes319** [comment]
just change your extension to .xyz for now.

**Comment by gabor1** [comment]
ASE changes its behaviour randomly... we are aware of it.

**Comment by bernstei** [comment]
> yesterday i can use extxyz and now i can't.

I'm actually _very_ surprised that using extxyz isn't working. If anything, I'd expect ASE to have decided that plain xyz is not for extxyz.

**Comment by bernstei** [comment]
> just change your extension to .xyz for now.

Did you actually change something in MACE to cause this change?

**Comment by stargolike** [comment]
> ASE changes its behaviour randomly... we are aware of it.

thanks, it's good method.

**Comment by stargolike** [comment]
> ASE changes its behaviour randomly... we are aware of it.

it sounds so sad :(

**Comment by stargolike** [comment]
> just change your extension to .xyz for now.

i solve the problem, thank you.

**Comment by stargolike** [comment]
> > just change your extension to .xyz for now.
> 
> @ilyes319 Did you actually change something in MACE to cause this change?

I newly reinstalled MACE, so I met this problem

**Comment by bernstei** [comment]
> > @ilyes319 Did you actually change something in MACE to cause this change?
> 
> I newly reinstalled MACE, so I met this problem

I was asking @ilyes319 if he intentionally changed anything in MACE to cause this.  Because there's really no reason it should start happening, unless he hard-wired something, which isn't a great idea.

**Comment by bernstei** [comment]
> > > @ilyes319 Did you actually change something in MACE to cause this change?
> > 
> > 
> > I newly reinstalled MACE, so I met this problem
> 
> I was asking @ilyes319 if he intentionally changed anything in MACE to cause this. Because there's really no reason it should start happening, unless he hard-wired something, which isn't a great idea.

Never mind - I see in the original post that started this thread that `.xyz` _is_ hardwired.   I stand by my statement that it should just defer to what ASE can read. A PR would be essentially trivial, but I don't know what branch to base it on.  @ilyes319 ?

**Comment by stargolike** [comment]
> > > @ilyes319 Did you actually change something in MACE to cause this change?
> > 
> > 
> > I newly reinstalled MACE, so I met this problem
> 
> I was asking @ilyes319 if he intentionally changed anything in MACE to cause this. Because there's really no reason it should start happening, unless he hard-wired something, which isn't a great idea.

 i use
'''

# Install PyTorch (for example, for CUDA 11.6 [cu116])
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

# Clone and install MACE (and all required packages)
git clone https://github.com/ACEsuit/mace.git
pip install ./mace
'''
today i reinstall MACE in a new machine, and i think when i'm running this command the lastest version ASE was installed.

**Comment by gabor1** [comment]
We could temporarily pin ASE 3.22 like everyone else...

**Comment by bernstei** [comment]
OMFG.  No.  This has _nothing_ to do with ASE's version. ".xyz" is hard-coded into MACE, for no good reason.

**Comment by bernstei** [comment]
> OMFG. No. This has _nothing_ to do with ASE's version. ".xyz" is hard-coded into MACE, for no good reason.

It needs to distinguish `.h5` from things that are read with `ase.io.read`, but that's the only issue.  It's easy to clean up, as soon as I know what branch to do it relative to.

**Comment by bernstei** [comment]
PR coming soon.

**Comment by ilyes319** [comment]
Fixed in main.
