### ISSUE TITLE
Training flag not working

### ISSUE THREAD

**Issue by ericyuan00000** [ACEsuit/mace#429]
**Describe the bug**

When running
```
python <mace_repo_dir>/mace/cli/run_train.py ... --pin_memory=False
```
the flag `pin_memory` remains `True`.

The code
```
parser.add_argument(
    "--pin_memory",
    help="Pin memory for data loading",
    default=True,
    type=bool,
)
```
in `arg_parser.py` does not seem to be the correct syntax.

**Comment by bernstei** [comment]
If the default is `True`, you could use `"--no_pin_memory", dest="pin_memory", action="store_false"`?

**Comment by bernstei** [comment]
Also, some additional alternatives including some more modern (py >= 3.9 specific) in https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

**Comment by ilyes319** [comment]
Fixed by string to bool type
