### ISSUE TITLE
why symmetric contraction doesn't work for some hidden irreps?

### ISSUE THREAD

**Issue by Fadelis98** [ACEsuit/mace#44]
### Discussed in https://github.com/ACEsuit/mace/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **Fadelis98** November  8, 2022</sup>
Although already mentioned in #36 that all degrees should have the same number of channels, I find it doesn't work for some certain irreps like 0o,1e. The error occurs in `cg.py`: line `117 current_ir = wigners[0][0]`, list out of range. Or in line `132 out += [last_ir, stack]`, last_ir not defined.

In the README guidance, it seems that these irreps are avoided on purpose, but I didn't see the reason in the MACE paper, could anyone  give me some insight?</div>

**Comment by davkovacs** [comment]
Can I close this issue, and just have it in the discussion?
