### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by niloufareabi** [ACEsuit/mace#453]
Hello dear developers,
I have problem with installing MACE. I'm in Iran , and I even tried it with proxy, but it didn't work.

> pip install mace-torch
Collecting mace-torch
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/e6/5f/7a95615c15b42e49d5f6d71d69b3a6399effe543264236dd7997673404ce/mace_torch-0.3.4-py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/e6/5f/7a95615c15b42e49d5f6d71d69b3a6399effe543264236dd7997673404ce/mace_torch-0.3.4-py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/e6/5f/7a95615c15b42e49d5f6d71d69b3a6399effe543264236dd7997673404ce/mace_torch-0.3.4-py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/e6/5f/7a95615c15b42e49d5f6d71d69b3a6399effe543264236dd7997673404ce/mace_torch-0.3.4-py3-none-any.whl.metadata
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/e6/5f/7a95615c15b42e49d5f6d71d69b3a6399effe543264236dd7997673404ce/mace_torch-0.3.4-py3-none-any.whl.metadata
**ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/e6/5f/7a95615c15b42e49d5f6d71d69b3a6399effe543264236dd7997673404ce/mace_torch-0.3.4-py3-none-any.whl.metadata (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)"))**

**Comment by nikhilss219** [comment]
I usually have this issue when my connection is behind a proxy wall. In my linux machine, I have added a proxy configuration in /etc/apt/apt.conf/proxy.conf (you can get a template of this file online). Afterwards, I have added a http_proxy and https_proxy as an environment variable in my ~/.bashrc. 

This error can also occur when you have not authenticated your proxy credentials. To resolve this, you can open your web browser and can enter your credentials when the proxy credentials are requested(comes as a pop up in firefox and chrome).

**Comment by stargolike** [comment]
it looks like network problem. you can visit to pypi and find this packege which named mace-torch. download it and install in your pc.

**Comment by stargolike** [comment]
it looks like network problem. you can visit to pypi and find this packege which named mace-torch. download it and install in your pc.

**Comment by niloufareabi** [comment]
> I usually have this issue when my connection is behind a proxy wall. In my linux machine, I have added a proxy configuration in /etc/apt/apt.conf/proxy.conf (you can get a template of this file online). Afterwards, I have added a http_proxy and https_proxy as an environment variable in my ~/.bashrc.
> 
> This error can also occur when you have not authenticated your proxy credentials. To resolve this, you can open your web browser and can enter your credentials when the proxy credentials are requested(comes as a pop up in firefox and chrome).

Thank you a a lot for your help, I will check this. I think you addressed it right.

**Comment by niloufareabi** [comment]
> it looks like network problem. you can visit to pypi and find this packege which named mace-torch. download it and install in your 

> it looks like network problem. you can visit to pypi and find this packege which named mace-torch. download it and install in your pc.

That's a good idea. I will definitely check it.

**Comment by CheukHinHoJerry** [comment]
If you can clone the repository, you can just build this from local by `cd mace`, `pip install .`?

**Comment by ilyes319** [comment]
@niloufareabi Any news on this issue?

**Comment by niloufareabi** [comment]
Hi dear @ilyes319 ,
First, Thank you for asking. And I have to say , the internet is never predictable in Iran, after several days of trying , it worked for no reason even without VPN. So, I installed it successfully.
But now I have problem with preparing the input data, I mean extended xyz file. I have done aimd in quantum espresso, is it possible to make an input from the output I got there? (Should I open a new issue?)

**Comment by gabor1** [comment]
Use ASE to process your QE output files, it can write extended xyz files as output

**Comment by niloufareabi** [comment]
> Use ASE to process your QE output files, it can write extended xyz files as output

Thanks for help, I've known this but I couldn't use it. So, I have to try more :)

**Comment by ilyes319** [comment]
@niloufareabi Nice, I'll close the issue.

**Comment by gabor1** [comment]
What was your problem with ASE?

**Comment by gabor1** [comment]
I suggest that you don't work from those files. Get ASE to read your QE output files directly, and write the result to extended xyz files.

**Comment by gabor1** [comment]
You can also assemble them by hand but make sure the units are right. The file format use documented in several places eg https://www.ovito.org/manual/reference/file_formats/input/xyz.html#

**Comment by niloufareabi** [comment]
Thanks a lot. I will try that 🙏🙏🙏

**Comment by niloufareabi** [comment]
Hello again,

I think ase.io.espresso can only read pw output. For ab-initio molecular
dynamics, it has 3 outputs of .for , .evp, and .pos
Is it possible to make an extended xyz file from those files with ase?
I saw the link you sent but I still really can't figure it out.

**Comment by gabor1** [comment]
I'm afraid we don't have the capacity to teach you python and ASE. if you have the data in arbitrary format, it is possible to process it into the specified extended XYZ. I recommend that you get local help with python/ASE.

**Comment by niloufareabi** [comment]
I understand.  Ok, sure.
Thank you anyway for your help and precious time🙏🙏
