### ISSUE TITLE
model not returning stress in the latest commit on `multi-head-interface`

### ISSUE THREAD

**Issue by CheukHinHoJerry** [ACEsuit/mace#481]
**Describe the bug**
Stresses returning from mace are all zero at commit `edc6b74`.

**To Reproduce**
two observations, the `rmse stress` not changing up to this number of digits like `0.05464624650477866` , or 

```python
mp0b_path = "mace_agnesi_medium.model"
model_mp0b = MACECalculator(model_paths=mp0b_path, device="cuda")
at.set_pbc(True) # some ase `Atoms`
at.set_calculator(model_mp0b)
print(at.get_stress()) # returns [0, 0, 0, 0, 0, 0]
```

Checking out to commit `122a50c` solves the problem (returning non-zero stress). Probably a bug introduced since then.

**Expected behavior**
matching stress return in commit `122a50c`.

I will try to see if I manage to fix this today.

**Comment by ilyes319** [comment]
what are the "some atoms" btw?

**Comment by ilyes319** [comment]
Actually I found the bug, just pushed a fix. Thank you!

**Comment by CheukHinHoJerry** [comment]
ah sorry I as in a meeting. Will try it now.

**Comment by CheukHinHoJerry** [comment]
Looks good. Thank you for fixing that.
