### ISSUE TITLE
CUDA out of memory from MD with MP-0 pre-trained model using 'big' geometry. 

### ISSUE THREAD

**Issue by turbosonics** [ACEsuit/mace#487]
**Describe the bug**
I tried to run LAMMPS MACE MD simulation with MACE-MP-0 pre-trained model (2024-01-07-mace-128-L2_epoch-199.model-lammps.pt, more precisely) from local GPU cluster environment, using a single GPU node (64 cores per node & 7.75gb mem per core ). 

I tested CaMg3O4 system. I found out 520 number of atoms with 4x4x4 supercell are OK and LAMMPS MD runs well using the pre-trained model. But when I even more supercell the system to make it more than 10k number of atoms and run MD simulation with the same model and the same 300K NVT MD setting, then CUDA OOM crash occur: 
`RuntimeError: CUDA out of memory. Tried to allocate 16.88 GiB. GPU`

This happens immediately after I submit the job, the LAMMPS couldn't even perform CG minimization, not even reached to the MD simulation stage. Here's my LAMMPS scripts:
 
```
# Setting
units           metal
atom_style      atomic
atom_modify     map yes
newton          on
dimension       3
#boundary        p p p
read_data       CaMg3O4_VASP_cellOPT_geoOPT_k666_c600_12x12x12_shifted.lmpdata
#read_restart

pair_style      mace no_domain_decomposition
pair_coeff      * * 2024-01-07-mace-128-L2_epoch-199.model-lammps.pt Ca Mg O
neighbor        1 bin
neigh_modify    every 10 delay 0 check no
timestep        0.001

# Minimization
log             log.01_opt
thermo_style    custom step cpu temp fmax fnorm pe ke density press pxx pyy pzz lx ly lz xlo xhi ylo yhi zlo zhi xy xz yz cella cellb cellc cellalpha cellbeta cellgamma
thermo          1
thermo_modify   norm no flush yes
dump            d01_opt all custom 1 dump_01_opt.lammps id type x y z fx fy fz
dump_modify     d01_opt sort id
min_style       cg
minimize        1.0e-7 1.0e-7 10000 10000
undump          d01_opt
write_data      data.after01_opt
write_restart   after01_opt.restart
reset_timestep  0

# NVTMD
log             log.02_relax
thermo_style    custom step cpu temp pe ke density press pxx pyy pzz lx ly lz xlo xhi ylo yhi zlo zhi
thermo          100
thermo_modify   norm no flush yes
restart         1000 02_relax.restart
velocity        all create ${temp1} 500000 mom yes rot yes dist gaussian
dump            d02_relax all custom 1 dump_02_relax.lammps id type x y z fx fy fz
dump_modify     d02_relax sort id
fix             nvt1 all nvt temp ${temp1} ${temp1} ${Tdamp}
run             ${iter01}
undump          d02_relax
unfix           nvt1
write_data      data.after02_relax
write_restart   after02_relax.restart
```

I followed instruction in https://mace-docs.readthedocs.io/en/latest/guide/lammps.html to compile LAMMPS-MACE module, except I used cuda 11.8 and gcc 11.2.0 and cudnn 8.1.1 for our local environment. And I also load those modules when I submit MACE LAMMPS simulation jobs. Like I wrote, test simulations run well with hundreds of atoms using MP-0 pretrained model, but it only crashes with CUDA OOM from 10k number of atoms. 

My questions are:  

1) Is this CUDA OOM can be escaped by more GPUs? Or, is this CUDA OOM limited by training set & training condition (in this case the MACE-MP-0) so that I wouldn't escape from CUDA OOM crash with any LAMMPS MD job conditions? 

2) If I fine-tune the MACE-MP-0 model with "big system" geometries, would that prevent CUDA OOM crash? 

3) What would be the tip or hint to escape from CUDA OOM crash, in general? 

Thanks

**Comment by stargolike** [comment]
At first, i think this is due to insufficient cuda memory. sometimes you need multi-gpu lammps.
Then, i meet the problem too. and i think it cant estimate how many atoms can run at maximum.
i use same parameters to train differemt system. However, training sets with more atoms and more complex structures can actually run larger systems in LAMMPS

**Comment by wcwitt** [comment]
I think 10k atoms is probably too many for your machine with this model. The long-term answer is multi-GPU. In the short term, you could try things like making the model less complex or reducing rmax.

**Comment by turbosonics** [comment]
> In the short term, you could try things like making the model less complex or reducing rmax.
Thanks! 

Is this means that I need to use the model from fine-tune training based on the MP-0 pretrained model with some less complicated training set & r_max of 4 or 5 (As far as I know, MP0 pre-trained model used r_max 6), to run MD simulation with 10k or more atoms? Am I understanding this correctly?

**Comment by stargolike** [comment]
> > 在短期内，您可以尝试降低模型的复杂性或降低 rmax 等方法。 谢谢！
> 
> 这是否意味着我需要使用基于 MP-0 预训练模型的微调训练模型，以及一些不太复杂的训练集和 4 或 5 的r_max（据我所知，MP0 预训练模型用于 6 r_max），以运行具有 10k 或更多原子的 MD 模拟？我理解正确吗？

using foundation_model=small or smaller r_max can do it

**Comment by turbosonics** [comment]
> using foundation_model=small or smaller r_max can do it

Thanks, I tested with "agnesi-small" from MP-0b pretrained model. The number of atoms without CUDA OOM crash increased to 6000 with single GPU node. I checked 8000 atoms bring CUDA OOM with Agnesi-Small from our GPU environment. But that is still not enough... 

It depends, but people typically run MD simulation with systems with 10k, even 100k order of magnitude of atoms. I wonder what hyperparameter setting would maintain reasonable accuracy yet enables to at least ~20k number of atoms. Do you have any idea?

**Comment by gabor1** [comment]
You really need parallel GPU evaluation for that. We're working on it. There is a parallel CPU evaluator that should be released soon (it's already working) that can scale to arbitrary sizes as long as you have enough CPU (tried >1M already)

**Comment by turbosonics** [comment]
> You really need parallel GPU evaluation for that. We're working on it. There is a parallel CPU evaluator that should be released soon (it's already working) that can scale to arbitrary sizes as long as you have enough CPU (tried >1M already)

Thanks, this is the best news I heard during July so far! I really hope the new version with parallel CPU and GPU support works well and become available for everyone soon! 

On the retrospect, maybe this explains why my attempts to use 2 or more nodes from our GPU and CPU clusters for LAMMPS-MACE have been failing. Maybe, at least from our environment, the current version of LAMMPS-MACE doesn't work well with multiple nodes, either GPU or CPU...

**Comment by wcwitt** [comment]
To expand on Gabor's comment, you need _efficient_ multi-GPU, which is still in progress. The multi-GPU/CPU that is available now does work, but it is inefficient, both in memory usage and compute speed. This is why our docs (currently) recommend against it.

It's only a guess, but I suspect your attempts failed for memory reasons. You can't use `no_domain_decomposition` for multi-GPU, which in effect means the memory requirements often go up, even if you spread the calculation over two GPUs.

**Comment by turbosonics** [comment]
> To expand on Gabor's comment, you need _efficient_ multi-GPU, which is still in progress. The multi-GPU/CPU that is available now does work, but it is inefficient, both in memory usage and compute speed. This is why our docs (currently) recommend against it.
> 
> It's only a guess, but I suspect your attempts failed for memory reasons. You can't use `no_domain_decomposition` for multi-GPU, which in effect means the memory requirements often go up, even if you spread the calculation over two GPUs.

Thanks, but multi-GPU and multi-CPU using mpirun from our local cluster environment doesn't work, even without no_domain_decomposition. I still see the CUDA OOM with just "pair_style mace" with 2 GPU nodes & mpirun. With "no_domain_decomposition", the error changes to "RuntimeError: CUDA error: device-side assert triggered" which also is related to the memory as far as I know.

**Comment by wcwitt** [comment]
Have you tried multi-GPU/CPU for a small test system (without `no_domain_decomposition`)?

**Comment by turbosonics** [comment]
> Have you tried multi-GPU/CPU for a small test system (without `no_domain_decomposition`)?

With 512 atom system with agnesi-small model with mpirun: 
- 2 GPU nodes with "pair_style mace": No crash, MD runs. 
- 2 GPU nodes with "pair_style mace no_domain_decomposition": Crash with "RuntimeError: CUDA error: device-side assert triggered" 

With 1000 atom system with agnesi-small model with mpirun: 
- 2 GPU nodes with "pair_style mace": Crash with CUDA OOM. 
- 2 GPU nodes with "pair_style mace no_domain_decomposition": Crash with "RuntimeError: CUDA error: device-side assert triggered" 
- 1 GPU node with "pair_style mace": Crash with CUDA OOM. 
- 1 GPU node with "pair_style mace no_domain_decomposition": No crash, MD runs. 

With agnesi-small model, 1 GPU node & "pair_style mace no_domain_decomposition", I can run up to ~6000 atoms. 

Here are modules I used: 
```
module load cuda11.8
module load cudnn/8.1.1.33-11.2-gcc-milan-a100
module load intel/2019
. /cm/shared/compilers/intel/2019/mkl/bin/mklvars.sh intel64
. /cm/shared/compilers/intel/2019/compilers_and_libraries/linux/bin/compilervars.sh intel64
module load openmpi/4.1.1-gcc-milan-a100
module load gcc/11.2.0
```

Hope these helps.

**Comment by wcwitt** [comment]
From this I would say things are working as expected. Although there is still much room to improve the efficiency!

First, the `no_domain_decomposition` option only makes sense for serial calculations, since LAMMPS inherently uses domain decomposition to parallelize over MPI processes. So let's pretend it that option doesn't exist. Importantly, `pair_style mace` (without `no_domain_decomposition`) requires MUCH more memory, which explains some of your observations. This is something we are working on now, as Gabor mentioned.

> With 512 atom system with agnesi-small model with mpirun:
>
>* 2 GPU nodes with "pair_style mace": No crash, MD runs.

This result suggests that you should be able run multi-GPU with as many GPUs as you like, provided you keep the number of atoms at 512 per GPU or lower. So, for 10k atoms, you may need 20 GPUs. I realize that is likely not practical or cost-effective for you - that's why we recommend against it for now.

Edit: I hadn't seen your update for CPU. That could be an installation issue, or it could simply be another memory issue - I'm not sure.

**Comment by turbosonics** [comment]
> From this I would say things are working as expected. Although there is still much room to improve the efficiency!
> 
> First, the `no_domain_decomposition` option only makes sense for serial calculations, since LAMMPS inherently uses domain decomposition to parallelize over MPI processes. So let's pretend it that option doesn't exist. Importantly, `pair_style mace` (without `no_domain_decomposition`) requires MUCH more memory, which explains some of your observations. This is something we are working on now, as Gabor mentioned.
> 
> > With 512 atom system with agnesi-small model with mpirun:
> > 
> > * 2 GPU nodes with "pair_style mace": No crash, MD runs.
> 
> This result suggests that you should be able run multi-GPU with as many GPUs as you like, provided you keep the number of atoms at 512 per GPU or lower. So, for 10k atoms, you may need 20 GPUs. I realize that is likely not practical or cost-effective for you - that's why we recommend against it for now.
> 
> Edit: I hadn't seen your update for CPU. That could be an installation issue, or it could simply be another memory issue - I'm not sure.

Thanks for your great replies. I will update CPU tests in this post as fast as I could, I have other things to do but I'm really interested to resolve this issue.

**Comment by wcwitt** [comment]
No need or urgency to update the CPU from my point of view. But if you feel your questions are answered, feel free to close this issue.

**Comment by turbosonics** [comment]
> No need or urgency to update the CPU from my point of view. But if you feel your questions are answered, feel free to close this issue.

I tested our CPU, it seems like opnmpi doesn't work with default libtorch so our cluster person compiled libtorch with mpi. But it turns out, multi-CPU core simulations are hopelessly slow from our environment, so we will just use GPU. May I ask when would be the timeframe of next LAMMPS-MACE for better parallel computing for multiple CPUs and multiple GPUs? 

Anyway, let me close this issue.
