### ISSUE TITLE
Dependencies pyproject.toml

### ISSUE THREAD

**Issue by galjos** [ACEsuit/mace#491]
Please put the dependencies in the `pyproject.toml`. This would make the installation way easier. Thanks.

```
[project]
dependencies = [
...
]
```

**Comment by ilyes319** [comment]
We are using the setup.cfg for installation. In which way would your change make it simpler?

**Comment by galjos** [comment]
Didn't see that. Then, please delete the dependency installation from your `README.md`, this confused me. And if we are already there, can you include `torch-dftd` to your dependencies.

**Comment by ilyes319** [comment]
This is an optional dependency, only used for a very restricted part of the code. As written in the readme, the recommanded way to install mace is through pypi that will automatically resolved dependencies.

**Comment by galjos** [comment]
Ok, then thanks for your time.
