### ISSUE TITLE
Inquiry about implement of `pair_repulsion` in the mace_mp function

### ISSUE THREAD

**Issue by hspark1212** [ACEsuit/mace#494]
Thank you for creating such an excellent repository!

I have questions regarding how `pair_repulsion` works in the MACE code. According to the code, when `pair_repulsion` is set to True (referred to this [line](https://github.com/ACEsuit/mace/blob/6671b5446d07e59d1a6a0db1bf0d82188916eee5/mace/modules/models.py#L91)), the potential is calculated using ZBLbasis and is then added to the energy of each node (referred to this [line](https://github.com/ACEsuit/mace/blob/6671b5446d07e59d1a6a0db1bf0d82188916eee5/mace/modules/models.py#L218)).

1. The [commit](https://github.com/ACEsuit/mace/commit/4a07e79c18ae6374197894702b7a4b52570e2211) adding `pair_repulsion` is dated March 28th. It seems it was not used during the pre-training of the mace_mp model. Does this imply that it is not incorporated in the `mace_mp` model?

2. I'm wondering if `pair_repulsion` is employed during training, or it is used as an additional feature on the trained models, similar to how the `TorchDFTD3Calculator` is used when `dispersion=True` in the `mace_mp` function?

3. Can `pair_repulsion` be activated using `from mace.calculator import mace_mp` by setting like `mace_mp(pair_repulsion=True)`?

**Comment by ilyes319** [comment]
Hey, 
 1. Pair repulsion was not used in the initial mace_mp models, but we released a new version of small and large that use it. You can find the models here: https://github.com/ACEsuit/mace-mp/releases/tag/mace_mp_0b.
 2. Yes it used both during training and evaluation.
 3. No you can not do that yet, you will have to path the url of the model to the mace_mp class as 
`macemp = mace_mp(model="https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0b/mace_agnesi_medium.model")`.

**Comment by hspark1212** [comment]
Thank you for your prompt response!

It would be nice if we could use `pair_repulsion` in the `mace_mp` function.

I've made a graph of the potential energy across the distance for Cu-Cu interactions, and it's working quite well!
![image](https://github.com/ACEsuit/mace/assets/64190846/7c72423b-8158-4e6d-a1d7-a48f9edfa91f)

**Comment by hspark1212** [comment]
Hi @ilyes319, I'm really enjoying using the mace model for my applications !

I have an additional question about `pair_repulsion` term.

From what I understand, when `pair_repulsion=True`, the ZBL potential is computed analytically and added to the MACE mdoel's energy. However, in the short-range (specifically when the distance is less than roughly about 1A), it seems like the MACE models' energy and the ZBL potential might be double counting or conflicting with each other. This could potentially lead to less accurate predictions compared to using the ZBL potential solely in the region.

I'm wondering your opinion about this.

Thanks in advance in your answer.

**Comment by ilyes319** [comment]
Dear @hspark1212,

You are right, this is why we always use a distance transforms that kills of mace at close approach on top of the ZBL potential. You can use --distance_transform="Agnesi" to use that.

**Comment by hspark1212** [comment]
Sounds smart. Thank you for the quick answer !

**Comment by ilyes319** [comment]
Note also that we fit the sum of ZBL and MACE at the same time, such that MACE has the flexibility to learn on top of the ZBL whenever there is sufficient data and we all MACE to have enough flexibility.

**Comment by hspark1212** [comment]
Thank you for your kind explanation with the reference paper.

I have a few more questions.

1. In the Cu-Cu distance graph, the potentials from `https://github.com/ACEsuit/mace-mp/releases/tag/mace_mp_0b` and the mace-mp-0 model appear almost identical. Do these models also show similar performance in the Matbench Discovery results?

2. I previously asked this, but since some time has passed, does setting `pair_repulsion=True` now work when finetuning in the current version?

3. If I want to finetune the model `https://github.com/ACEsuit/mace-mp/releases/tag/mace_mp_0b` that was originally trained with `pair_repulsion=True`, should I also set `pair_repulsion=True` during finetuning?
