### ISSUE TITLE
ASE documentation update?

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/mace#531]
Referring to https://mace-docs.readthedocs.io/en/latest/guide/ase.html.

Can we remove or update this now?

> The native ASE neighbour list being slow, it is recommended to use the matscipy [branch](https://github.com/ACEsuit/mace/tree/52-matscipy-neighbour-list-as-default). Note that the matscipy branch is not compatible with non-periodic systems.

**Comment by ilyes319** [comment]
yes we can remove that, nice catch!

**Comment by wcwitt** [comment]
What about the warning for non-periodic systems? Should that stay or go?

**Comment by wcwitt** [comment]
I made a PR - if you want anything else just LMK.

**Comment by ilyes319** [comment]
perfect thank you.
