### ISSUE TITLE
Bug on loading finetuning model

### ISSUE THREAD

**Issue by hspark1212** [ACEsuit/mace#545]
First, thank you for creating this excellent repository! I have encountered a bug while trying to load a fine-tuning model in main branch.

# Steps to Reproduce
## 1. Create a Simple Dataset for Fine-Tuning

I created a simple dataset for fine-tuning using the ase library as follows:
```
from ase.build import bulk
from ase.io import write
import numpy as np

# Create a bulk aluminum structure
atoms = bulk("Al", "fcc", a=4.05, cubic=True)

# Assign energy and forces to the atoms object
atoms.info["energy"] = -3.77
atoms.info["forces"] = np.zeros((len(atoms), 3))

# Write the atoms object to a file
write("test.xyz", [atoms])
```
## 2. Run the Fine-Tuning Process
I followed the instructions provided in the repository's README and executed the fine-tuning code with epoch=0, aiming to load the model without any training:
```
mace_run_train \
  --name="mace-mp-test" \
  --foundation_model="medium" \
  --train_file="test.xyz" \
  --valid_file="test.xyz" \
  --test_file="test.xyz" \
  --energy_weight=1.0 \
  --forces_weight=1.0 \
  --E0s="average" \
  --lr=0.0001 \
  --scaling="rms_forces_scaling" \
  --batch_size=1 \
  --valid_batch_size=1 \
  --max_num_epochs=0 \ # (max_num_epoch is set to 0 !)
  --ema \
  --ema_decay=0.99 \
  --amsgrad \
  --save_all_checkpoints \
  --default_dtype="float64" \
  --device=cuda \
  --eval_interval=1 \
  --seed=42 
  ```
  ## 3. Load the Fine-Tuned model
I loaded the fine-tuned model and compared it to the original foundation model using the mace calculator:
  ```
 from ase.io import read
from mace.calculators import mace_mp

# Read the test data
atoms = read("test.xyz", ":")[0]

# Initialize calculators for both models
mace_calc = mace_mp("medium", device="cuda", default_dtype="float32")
mace_test_calc = mace_mp(
    "mace-mp-test_compiled.model", device="cuda", default_dtype="float32"
)

# Compare potential energies
original_energy = mace_calc.get_potential_energy(atoms)
finetuned_energy = mace_test_calc.get_potential_energy(atoms)

print(original_energy, finetuned_energy)
```

output
```
(-14.912947654724121, 0.7345788478851318)
```

## Expected Behavior
The potential energy values from the foundation model and the fine-tuned model should be the same, as there was no training performed (i.e., max_num_epochs=0).

## Actual Behavior
The energy output from the fine-tuned model differs significantly from the foundation model's output.

## Conclusion
It seems there might be an issue with how the fine-tuning model is loaded or initialized. Any guidance or suggestions on resolving this discrepancy would be greatly appreciated.

**Comment by ilyes319** [comment]
The E0s will change if you use E0s="average" so I don't expect the result no to change. You can use E0s="foundation", if you want to reuse the E0s of the foundation model.

**Comment by hspark1212** [comment]
It works well ! Thank you for this prompt answering !
