### ISSUE TITLE
Colab Tutorial Link Does not work

### ISSUE THREAD

**Issue by RBERLOP** [ACEsuit/mace#563]
I am a new user of MACE software and I have read most of the documentation. 
As an starting point, the documentators encourage you to complete this "Colab tutorial"  that can be found at the end of the MD section.
https://mace-docs.readthedocs.io/en/latest/guide/ase.html#running-md-simulations
When I click the button "here" (which links to this website: https://colab.research.google.com/drive/1D6EtMUjQPey_GkuxUAbPgld6_9ibIa-V?authuser=1#scrollTo=wfCwdnaWv9rd )  It pops a new tab to the tutorial. However, I cannot do the tutorial because apparently something is wrong with the google account.
![image](https://github.com/user-attachments/assets/b0e9b8d4-7aa1-4207-815f-a0bda4518af6)

As it says (in spanish): "The notebook cannot be loaded. Confirm that you have acces to the file and try again."
When I click to the link  below:
https://drive.google.com/drive/?action=locate&id=1D6EtMUjQPey_GkuxUAbPgld6_9ibIa-V&authuser=1 
It sends me to my google drive shared folder but nothing happens. I couldn't find any new document added to my shared folder

As an expected behaviour... I expected the tutorial to be opened.

 - OS: Ubuntu 22.04
 - Browser Mozilla Firefox 129.0.2

I want to do the tutorials because I was previously working with VASP to train ML FF for a given system and I want to start using MACE but the environment, flags and workflow is quite different. 

Hope you can help me on this, Thank you very much in advance

Ramon Bergua

**Comment by RBERLOP** [comment]
Update:

I could open the colab link:  https://colab.research.google.com/drive/1D6EtMUjQPey_GkuxUAbPgld6_9ibIa-V?authuser=1#scrollTo=wfCwdnaWv9rd    by switching to a private window and opening by hand. It should be related my google account.

**Comment by gabor1** [comment]
OK. Let us know if you encounter any difficulties. I'm closing the issue.
