### ISSUE TITLE
help message for `--pair_repulsion` is wrong

### ISSUE THREAD

**Issue by njzjz** [ACEsuit/mace#565]
**Describe the bug**

https://github.com/ACEsuit/mace/blob/575af0171369e2c19e04b115140b9901f83eb00c/mace/tools/arg_parser.py#L129-L134

I believe this message is copied from

https://github.com/ACEsuit/mace/blob/575af0171369e2c19e04b115140b9901f83eb00c/mace/tools/arg_parser.py#L486-L491

**Comment by ilyes319** [comment]
Thanks I have fixed it.
