### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by simonbatzner** [ACEsuit/mace#57]
Hi all, I'm trying to reproduce the results on 3BPA from the paper for L=2 but am getting significantly worse results so far. I've tried a number of different setups already (see below), based on parameters that I saw in the code code but that were never reported in the paper so I thought they might be the culprit, but so far that doesn't seem to be the reason. What am I doing wrong?

The paper reports an error in the F-RMSE of 8.8 meV/A on T=300K on 3BPA. I trained the following 5 setups but was only able to get a best error of about 10.9 meV/A. Here's what I ran 

```
python $~/harvard_internal_path/mace/scripts/run_train.py \
    --name="MACE_model" \
    --train_file="~/harvard_internal_path/3bpa/dataset_3BPA/train_300K.xyz" \
    --valid_fraction=0.1 \
    --test_file="~/harvard_internal_path/3bpa/dataset_3BPA/test_300K.xyz" \
    --config_type_weights='{"Default":1.0}' \
    --E0s='{1:-13.663181292231226, 6:-1029.2809654211628, 7:-1484.1187695035828, 8:-2042.0330099956639}' \
    --model="MACE" \
    --hidden_irreps='256x0e + 256x1o + 256x2e' \
    --r_max=5.0 \
    --batch_size=5 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --restart_latest \
    --device=cuda \
    --clip_grad=None
```

which gives an error of ~11.6 meV/A: 

```
+-------------+---------------------+------------------+-------------------+
| config_type | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % |
+-------------+---------------------+------------------+-------------------+
|    train    |         0.1         |       3.8        |        0.40       |
|    valid    |         0.1         |       11.5       |        1.19       |
|   Default   |         0.1         |       11.6       |        1.20       |
+-------------+---------------------+------------------+-------------------+
```

And here are the modifications I tried: 

- add SWA, train longer: 13.2 meV/A
- add gradient clipping, train longer: 11.5 meV/A
- add SWA + gradient clipping, train longer: 13.7 meV/A
- use ScaleShiftMACE, no clip, no SWA, default epochs: 10.9 meV/A

Since the last one is a pretty significant change, here the full config: 

```
python $harvard_internal_path/mace/scripts/run_train.py \
    --name="MACE_model" \
    --train_file="harvard_internal_path//3bpa/dataset_3BPA/train_300K.xyz" \
    --valid_fraction=0.1 \
    --test_file="harvard_internal_path//3bpa/dataset_3BPA/test_300K.xyz" \
    --config_type_weights='{"Default":1.0}' \
    --E0s='{1:-13.663181292231226, 6:-1029.2809654211628, 7:-1484.1187695035828, 8:-2042.0330099956639}' \
    --model="ScaleShiftMACE" \
    --hidden_irreps='256x0e + 256x1o + 256x2e' \
    --r_max=5.0 \
    --batch_size=5 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --restart_latest \
    --device=cuda \
    --clip_grad=None
```

````
+-------------+---------------------+------------------+-------------------+
| config_type | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % |
+-------------+---------------------+------------------+-------------------+
|    train    |         0.2         |       5.0        |        0.53	   |
|    valid    |         0.2         |       10.7       |        1.11	   |
|   Default   |         0.2         |       10.9       |        1.13	   |
+-------------+---------------------+------------------+-------------------+
````

These are all "Default" errors which I assume is the test set file I pass?

I must be missing something major? Can you help out?

Related to this: there also seem to be options that are by default on in the code that are never reported, e.g. SWA together with all its parameters and gradient clipping. Were they used in the paper or not? I cannot find a mention in the paper which seems like a clear no to me, but they seem to be on by default in the code. I also didn't see a git commit reported in the paper or a version for the code to reproduce? What was actually run for the paper? Can you share complete input + data files + code versions to reproduce?

Finally, I'd also like to compute test errors separately using the eval script (as opposed to at the end of training), but get this error: 

```
Traceback (most recent call last):
  File "~/harvard_internal_path/mace/scripts/eval_configs.py", line 113, in <module>
    main()
  File "~/harvard_internal_path/mace/scripts/eval_configs.py", line 59, in main
    z_table = tools.AtomicNumberTable([int(z) for z in model.atomic_numbers])
AttributeError: 'dict' object has no attribute 'atomic_numbers'
```

Thanks!

**Comment by ilyes319** [comment]
Hi,

There has been a lot of changes to the defaults parser, to have more robust hypers but that are quite different to the one used in the paper. In particular the default weights in the loss.

This input should be able to reproduce it on the develop branch. 


```
python ./mace-main/scripts/run_train.py \
    --name="MACE_3bpa" \
    --train_file="train_300K.xyz" \
    --valid_fraction=0.1 \
    --test_file="test.xyz" \
    --energy_weight=27.0 \
    --forces_weight=1000.0 \
    --config_type_weights='{"Default":1.0}' \
    --E0s='{1: -13.587222780835477, 6: -1029.4889999855063, 7: -1484.9814568572233, 8: -2041.9816003861047}' \
    --model="ScaleShiftMACE" \
    --interaction_first="RealAgnosticResidualInteractionBlock" \
    --interaction="RealAgnosticResidualInteractionBlock" \
    --num_interactions=2 \
    --max_ell=3 \
    --hidden_irreps='256x0e + 256x1o + 256x2e' \
    --num_cutoff_basis=5 \
    --correlation=3 \
    --r_max=5.0 \
    --scaling='rms_forces_scaling' \
    --batch_size=5 \
    --max_num_epochs=2000 \
    --patience=256 \
    --weight_decay=5e-7 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --default_dtype="float32"\
    --clip_grad=None \
    --device=cuda \
    --seed=3 \
```

On the question of added functionalities, they were not used in the code and added later to provide more robust defaults. It is on continuous development. I have linked here a zip file with the *original* code used for the paper, and the original input file. 
The dataset can be found in the following repo : https://github.com/davkovacs/BOTNet-datasets .

For the last question on the eval script, did you make sure to use the `.model` file? As opposed to the `.pt`

Please let me know if you have any other questions. In case it is needed, I have attached the copy of the code and the input script that I have used for the paper, if we stumble into compatibility problems.

Looking forward to hear from you.
Ilyes
[reproduce_mace.zip](https://github.com/ACEsuit/mace/files/10202556/reproduce_mace.zip)

**Comment by simonbatzner** [comment]
Awesome, this worked. Thanks a lot.
