### ISSUE TITLE
MACE with latest version of LAMMPS, giving error

### ISSUE THREAD

**Issue by ShubhangG** [ACEsuit/mace#587]
Hi,

In the the installation documentation of [MACE with LAMMPS](https://mace-docs.readthedocs.io/en/latest/guide/lammps.html), a very old version of lammps is forked into the MACE github. I installed a recent version of LAMMPS and followed the installation exactly as the link suggested. The installation went smoothly, the package ML-MACE installed smoothly.

But when I ran a simple LAMMPS run, the lammps output file raised an error that pair_style mace does not exist. 

Is there a way I can fix that, and use the latest version of lammps and not rely on the old forked version of lammps given in the MACE documentation?

**Comment by wcwitt** [comment]
For now, the only option is our fork. Is there a particular reason you need the very latest LAMMPS? Or is it just that you don't like having multiple installations.

**Comment by ShubhangG** [comment]
I just need a later version of lammps. I want to run ipi -- path integral MD code which handshakes with LAMMPS using our MACE model. They recently updated their code to interface with LAMMPS better and I wanted to update lammps so that I could do MACE+LAMMPS+Ipi Pimd.

**Comment by wcwitt** [comment]
We have already started the process of bringing our fork up to date with this year's LAMMPS release. Until recently, there hasn't been any good reason to do so, but it's probably worthwhile now. Do you know whether you need the current `develop`, `release`, or `stable`?

**Comment by ShubhangG** [comment]
The current stable release will be great. Not necessary for develop.

**Comment by wcwitt** [comment]
This branch is based of the current LAMMPS `release` branch: https://github.com/ACEsuit/lammps/tree/mace-develop. It builds (and works, as far as I know) but I haven't tested much yet.

**Comment by ShubhangG** [comment]
Oh thank you so much! I will check it out and test a few runs this coming month.

Thanks a lot!

**Comment by wcwitt** [comment]
Sometime soon I will make this new branch the default. I will close this issue for now, but don't hesitate to re-open if you encounter any problems.

**Comment by wcwitt** [comment]
@ShubhangG were you able to try the `mace-develop` branch, and, if yes, did it work reasonably for you?

**Comment by ShubhangG** [comment]
Hey I will let you all know in this thread once I update and try things out... I plan to use some of the thanksgiving break to make some updates and test things..sorry have this particular paper deadline I'm trying to meet on this other project. 

Will keep you in the loop, thanks!

**Comment by vishank-u** [comment]
Hi, I faced the same issue where LAMMPS is not recognizing the "pai_style" mace. Here is the error:

```
ERROR: Unrecognized pair style 'mace' (src/force.cpp:275)
Last command: pair_style mace no_domain_decomposition
```

I have installed the latest version of mace-torch 0.3.10 frrom github and installed LAMMPS 29Aug2024 stable release. I added 
`-D PKG_ML-MACE=ON ` while compiling but still it does not recognize the pair_style. Will you please let me know which stable/release version of LAMMPS should I try?

**Comment by ilyes319** [comment]
did you follow the installation in the documentation?

**Comment by vishank-u** [comment]
Hi Ilyes,

Yes I followed the installation instructions:

1. Convert .model file to lammps .pt file
2. Install mace (I did from source using pip install ./mace
3. Compile LAMMPS with the settings mentioned 

Mace is working fine as a standalone I checked and also generated the lammps .pt file but lammps is not recognising the pair style and I thought it is the version issue as I see in the thread above but it does not mention which version of LAMMPS supports this now?

**Comment by ilyes319** [comment]
As mentioned here; you need to install this fork of lammps https://github.com/ACEsuit/lammps. Did you make sure to use that?

**Comment by vishank-u** [comment]
Okay thanks, I will install this fork repo of LAMMPS and will get back to you if I face any issue. Thanks

**Comment by ilyes319** [comment]
Please make sure to follow the documentation step by step: https://mace-docs.readthedocs.io/en/latest/guide/lammps.html

**Comment by vishank-u** [comment]
Hi Ilyes,

I am building it on LUMI cluster that uses AMD and rocm compilers for PyTorch. I have installed PyTorch already but it is still asking for torch cmake while compiling LAMMPS:

```
CMake Error at Modules/Packages/ML-MACE.cmake:3 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.
```

I do not know if you have tried installing this for AMD GPUs!.

**Comment by vishank-u** [comment]
Hi,

I installed the fork repo of LAMMPS following the installation and converted my `.model` file `.pt` file for LAMMPS as suggested: https://mace-docs.readthedocs.io/en/latest/guide/lammps.html#preparing-your-model. I have also installed the LAMMPS fork repository as suggested. I am running on AMD with ROCM compiler and the simulation works fine for small toy system of 16 atoms but gives memory error with only 250 atoms. I am attaching my lammps file, and slurm outputs.

1. Input: [in.lammps.txt](https://github.com/user-attachments/files/18888401/in.lammps.txt)
2. Output with 16 atoms: [slurm-9591660_queue.out.txt](https://github.com/user-attachments/files/18888400/slurm-9591660_queue.out.txt)
3. Output with 250 atoms: [slurm-9609217_queue.out.txt](https://github.com/user-attachments/files/18888398/slurm-9609217_queue.out.txt)
4. Error with 250 atoms: [error.log](https://github.com/user-attachments/files/18888399/error.log)

I am submitting on a single GPU and even tried giving memory of the whole node (256 Gb)

 I am wondering if I am making some mistake in the input file or something wrong in the installation to make it so memory intensive. And if it is an issue from LAMMPS/MACE side or from hardware side!

Thanks for having a look.

**Comment by moonsheeeeeep** [comment]
May I ask if LAMMPS MACE is currently unable to perform mpirun parallel computing? I tried that single core can run. But multi-core parallel will report an error.
