### ISSUE TITLE
Loosen the dependency to avoid conflict with other package

### ISSUE THREAD

**Issue by chiang-yuan** [ACEsuit/mace#588]
@ilyes319 could we loosen the dependency of e3nn to `e3nn>=0.4.4`

https://github.com/ACEsuit/mace/blob/22a2e3e9b47a50a5a2723abcd9fe6afd0bb9695f/setup.cfg#L18

**Comment by ilyes319** [comment]
Can you try locally updating to the latest e3nn and see if everything training works.

**Comment by chiang-yuan** [comment]
I am trying to wrap a pyproject.toml dependency. `e3nn` is the only one cause the problem. Locally updating is possible for user but not package wrapping unfortunately. :(

**Comment by chiang-yuan** [comment]
Not sure at this moment. I could update locally and try training for the next model. Another way is test workflow? Is there anything missing in the test that we should probably add?

**Comment by ilyes319** [comment]
big missing part in the testing workflow atm are training with h5 files and multigpu (that one we can't not really test).

**Comment by chiang-yuan** [comment]
I see. I will try adding offline testing script and small demo data. And pick up #452 and solve it altogether

**Comment by chiang-yuan** [comment]
related to #555
