### ISSUE TITLE
Example of using pretrained foundation models in LAMMPS

### ISSUE THREAD

**Issue by ChiahsinChu** [ACEsuit/mace#593]
Hi,

I was trying to use the foundation model MACE-MP for my project. However, I only found the example with ASE calculator for MD simulations in the doc. Would it be possible to use the foundation model (without fine-tuning) in LAMMPS?

Thanks.

**Comment by ilyes319** [comment]
Hello @ChiahsinChu,

You need to follow these steps:
1. Download the model here: https://github.com/ACEsuit/mace-mp/releases/tag/mace_mp_0
2. Transform the model into a lammps model: https://mace-docs.readthedocs.io/en/latest/guide/lammps.html
3. Run the model in lammps using the rest of documentation.

**Comment by ChiahsinChu** [comment]
Thanks for your kind reply!
