### ISSUE TITLE
Is there a tag I can use to save most recent or last epoch as my checkpoint?

### ISSUE THREAD

**Issue by ankitmathanker** [ACEsuit/mace#606]
As my training sample size is increasing, to train a model with 1000 epoch, I am required to restart the calculations. At present everytime I restart the model the run starts from a saved checkpoint and it doesn't save any next checkpoint before the run terminates with allocation time issue. So I am currently unable to continue the run to finish as there is no progress point saved.

If there happens to be a tag I can use to ask model to save a checpoint after certain number of epoch and restart the run from there this should help.

I am currently not able to find a direct solution for this from documentation.

**Comment by ilyes319** [comment]
You can use the tag `--save_all_checkpoints` that will save all the checkpoints during training. You to find different options you can run mace_run_train --help.
