### ISSUE TITLE
Errors when using mace in combination with lammps.

### ISSUE THREAD

**Issue by fhfeng21** [ACEsuit/mace#611]
1. according to the prompt of "https://mace-docs.readthedocs.io/en/latest/guide/lammps.html", install lammps that can run mace potential function.
2. Then download the potential function on https://github.com/ACEsuit/mace-mp/releases/tag/mace_mp_0.
3. When trying to use this potential function, the following error occurs

Loading MACE model from "2024-01-07-mace-128-L2_epoch-199.model" ...terminate called after throwing an instance of 'c10::Error'
  what():  PytorchStreamReader failed locating file constants.pkl: file not found
Exception raised from valid at ../caffe2/serialize/inline_container.cc:177 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x2ad46496956e in /data/fhf/soft/tongyongshi/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5c (0x2ad464933f18 in /data/fhf/soft/tongyongshi/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::PyTorchStreamReader::valid(char const*, char const*) + 0x8e (0x2ad468e5ec4e in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #3: caffe2::serialize::PyTorchStreamReader::getRecordID(std::string const&) + 0x46 (0x2ad468e5edd6 in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #4: caffe2::serialize::PyTorchStreamReader::getRecord(std::string const&) + 0x45 (0x2ad468e5ee85 in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #5: torch::jit::readArchiveAndTensors(std::string const&, std::string const&, std::string const&, c10::optional<std::function<c10::StrongTypePtr (c10::QualifiedName const&)> >, c10::optional<std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, caffe2::serialize::PyTorchStreamReader&, c10::Type::SingletonOrSharedTypePtr<c10::Type> (*)(std::string const&), std::shared_ptr<torch::jit::DeserializationStorageContext>) + 0xa5 (0x2ad469f205e5 in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x4d20507 (0x2ad469f0b507 in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x4d2324b (0x2ad469f0e24b in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #8: torch::jit::import_ir_module(std::shared_ptr<torch::jit::CompilationUnit>, std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x3a2 (0x2ad469f0fc82 in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #9: torch::jit::import_ir_module(std::shared_ptr<torch::jit::CompilationUnit>, std::string const&, c10::optional<c10::Device>) + 0x7b (0x2ad469f1039b in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #10: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0xa5 (0x2ad469f10475 in /data/fhf/soft/tongyongshi/libtorch/lib/libtorch_cpu.so)
frame #11: ../lammps/build/lmp() [0x8a4b98]
frame #12: ../lammps/build/lmp() [0x49d397]
frame #13: ../lammps/build/lmp() [0x4a285e]
frame #14: ../lammps/build/lmp() [0x4a30ed]
frame #15: ../lammps/build/lmp() [0x4815e8]
frame #16: __libc_start_main + 0xf5 (0x2ad47fbe7b15 in /usr/lib64/libc.so.6)
frame #17: ../lammps/build/lmp() [0x482af9]

**Comment by wcwitt** [comment]
It looks like you may have skipped this part:

https://mace-docs.readthedocs.io/en/latest/guide/lammps.html#preparing-your-model

**Comment by fhfeng21** [comment]
Thank you very much for your reply. As you said, I tried the command "Python mace/mace/CLI/create _ LAMPS _ model.py2024-01-07-mace-128-L2 _ EPOCH-199. Model", which generated a potential function suitable for LAMPS and solved this problem.
