### ISSUE TITLE
python 3.9 support foiled by trivial syntax

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#617]
The syntax for the argument hints used by `MACECalculator` is not supported by python 3.9, but otherwise things are fine (specifically `model_paths`, `device`, and `models`).  Would it be OK to get rid of the `| None` in those 3 lines?

**Comment by ilyes319** [comment]
yes lets get rid of that.

**Comment by bernstei** [comment]
I'll do a little PR if no one else beats me to it
