### ISSUE TITLE
load_from_xyz() got an unexpected keyword argument 'head_key'

### ISSUE THREAD

**Issue by cecilia-hong** [ACEsuit/mace#627]
I am trying to train a MACE model from scratch and after pulling the recent changes, I am getting this error when I try to run the run_train.py. 

Traceback (most recent call last):
  File "/exports/eddie/scratch/s1737494/mace/struc_a/ch_3/run_train.py", line 783, in <module>
    main()
  File "/exports/eddie/scratch/s1737494/mace/struc_a/ch_3/run_train.py", line 63, in main
    run(args)
  File "/exports/eddie/scratch/s1737494/mace/struc_a/ch_3/run_train.py", line 200, in run
    collections, atomic_energies_dict = get_dataset_from_xyz(
  File "/exports/csce/eddie/chem/groups/Hobday/Cecilia/anaconda3/envs/mace_new/lib/python3.10/site-packages/mace/tools/scripts_utils.py", line 54, in get_dataset_from_xyz
    atomic_energies_dict, all_train_configs = data.load_from_xyz(
TypeError: load_from_xyz() got an unexpected keyword argument 'head_key'

I would really appreciate it if you can suggest how I can get about this. Many thanks in advance!

**Comment by cecilia-hong** [comment]
I should have also mention, I had been able to do this training on the same dataset and arguments fed to the program a couple weeks back.

**Comment by ilyes319** [comment]
You must have an incorrect installation. Make sure to uninstall mace fully and then reinstall it to the main branch.

**Comment by cecilia-hong** [comment]
Hello, 

Thank you for your quick response.
Unfortunately, I cannot seem to be able to attached my py env and input script for the training here so I have emailed it to you if thats alright. 

So the steps that I had initially followed when instally mace in August were (after making the conda env and having gpu support) :

git clone https://github.com/ACEsuit/mace.git
conda install pytorch=2.2.0 torchvision=0.17.0 torchaudio=2.2.0 pytorch-cuda=11.8  -c pytorch -c nvidia
pip install mace-torch

Would you mind advising where I might have gone wrong with the versions please?

Many thanks in advance

**Comment by ilyes319** [comment]
Hey @cecilia-hong,  for you for sending your env. Indeed two different versions are installed. You have both the pypi 0.3.6 and the main branch clone.

Please can you do the following:

```
pip uninstall mace-torch
pip install git+https://github.com/ACEsuit/mace.git@main
```

Then instead of running: `python run_train.py` to train your model, run:

```
mace_run_train \
    --name="model" \
    --restart_latest \
    --train_file="train.xyz" \
    --valid_file="valid.xyz" \
```

**Comment by cecilia-hong** [comment]
Hello, 
Thank you so much for your help and getting back to me so quickly! 
I will follow your steps when gpu resources become available again on my hpc!
