### ISSUE TITLE
NaCl cube example missing in drive (example-xyz-movie/aqueous interface/NaCl_cube)

### ISSUE THREAD

**Issue by dgvalcarce** [ACEsuit/mace#640]
First of all, thank you for uploading these movies, they are really helpful for people starting to work with MACE.

I want to simulate dissolution processes with MACE, so the example of the NaCl cube surrounded by water would be very useful for me. I noticed is the only one missing in this folder. If you could upload it, it would be very helpful.

Thank you very much, 
David.

**Comment by vue1999** [comment]
Dear David,

I apologize for the missing file—I've now uploaded the NaCl cube example. Please feel free to reach out if you need any further details.

Best,
Eszter
