### ISSUE TITLE
Simulations/Energy minimizations on multiple GPUs with MACE/ASE

### ISSUE THREAD

**Issue by betterwithchem** [ACEsuit/mace#649]
Hi,

I'm wondering if it is possible to run MD simulations and Energy minimizations with MACE in ASE using multiple GPUs. The SLURM script I'm using at the moment is:

```
#!/bin/bash --login

#SBATCH --job-name=min_mace-off
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --time=06:00:00

conda activate mace_env
export CUDA_VISIBLE_DEVICES=0,1,2,3
srun --gpus=4 --ntasks=1 python3 ./em_off.py

```

But it only uses on the first GPU (checked with `nvidia-smi`). I've also tried adding `nvidia-cuda-mps-control -d` before launching python, but the result is the same.

Thanks in advance!

**Comment by gabor1** [comment]
are you suggesting this because you have large systems? up to about 1000 atoms, a single GPU is likely optimal. We are working on efficient multi-GPU evaluation, but it's not quite ready yet. It will be likely via lammps though, not ASE (but of course you can call lammps from ASE, via lammpslib)

**Comment by gabor1** [comment]
the 1000 atoms above were for A100 80 GB GPUs. if your memory is smaller, you will find that smaller systems are already optimal of course.

**Comment by ilyes319** [comment]
It is not supported for now. It will become possible with LAMMPs soon.
