### ISSUE TITLE
Run time Error after training model using tutorial dataset 

### ISSUE THREAD

**Issue by spriti523** [ACEsuit/mace#665]
Trained the model with ethanol-methanol dataset in the tutorial, with the following input configuration, getting the following error after completion of training and while evaluation.

```
class RealAgnosticInteractionBlock(Module):
  __parameters__ = []
Traceback of TorchScript, original code (most recent call last):
  File "/nas/longleaf/home/sampriti/.conda/envs/fhi-vibes/lib/python3.10/site-packages/mace/modules/models.py", line 338, in forward

        # Atomic energies
        node_e0 = self.atomic_energies_fn(data["node_attrs"])
                  ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        e0 = scatter_sum(
            src=node_e0, index=data["batch"], dim=-1, dim_size=num_graphs
  File "/nas/longleaf/home/sampriti/.conda/envs/fhi-vibes/lib/python3.10/site-packages/mace/modules/blocks.py", line 146, in forward
        self, x: torch.Tensor  # one-hot of elements [..., n_elements]
    ) -> torch.Tensor:  # [..., ]
        return torch.matmul(x, self.atomic_energies)
               ~~~~~~~~~~~~ <--- HERE
RuntimeError: expected scalar type Double but found Float
```

The model has been trained using the following inputs

```
mace_run_train --name="MACE_model" \
    --train_file="modified_eth_meth_train.xyz" \
    --valid_fraction=0.05 \
    --test_file="modified_eth_meth_test.xyz" \
    --config_type_weights='{"Default":1.0}' \
    --energy_key="new_energy" \
    --loss='weighted' \
    --energy_weight=80 \
    --E0s='{1:-13.663181292231226, 6:-1029.2809654211628, 7:-1484.1187695035828, 8:-2042.0330099956639}' \
    --model="MACE" \
    --hidden_irreps='128x0e + 128x1o' \
    --correlation=3 \
    --max_L=2 \
    --r_max=6.0 \
    --batch_size=50 \
    --max_num_epochs=200 \
    --seed=123 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --default_dtype="float32" \
    --swa \
    --error_table='PerAtomRMSE' \
    --restart_latest
```

**Comment by ilyes319** [comment]
Hello,
Can you post your full log file please so I can help you.

**Comment by spriti523** [comment]
Yes, here it is. 
[MACE_model_run-123.log](https://github.com/user-attachments/files/17578068/MACE_model_run-123.log)

Thanks!

**Comment by ilyes319** [comment]
I don't see any error here, where are you seeing this error exactly?

**Comment by spriti523** [comment]
Apologies for the misunderstanding. The above error comes when I use the model for evaluation, I use following configuration syntaxes. I have used other  compiled models and swa types as well. 

mace_eval_configs \
    --configs="modified_eth_meth_test.xyz" \
    --model="MACE_model.model" \
    --output="my_output.xyz"

**Comment by ilyes319** [comment]
Ah ok you need to add `--default_dtype="float32"` to your input. Also looking at your log, you probably are using the wrong E0s or have the wrong units. From what tutorial did you find the xyz file?

**Comment by spriti523** [comment]
Oh okay alright, thanks. And I am using isolated atom energies as E0s from  BOTnet-datasets. They are in eV (as per DFT energy ranges ) . 
Also, I do not know if this is relevant, but I am training with the interaction energies i.e total energy-energy of each atom, in that case, do the E0s need  0s in that case?

The following is the isolated atoms file. 
1
Properties=species:S:1:pos:R:3 config_type=isolated_atom energy=-13.568422383046626 pbc="F F F"
H        0.00000000       0.00000000       0.00000000
1
Properties=species:S:1:pos:R:3 config_type=isolated_atom energy=-1025.2770951782686 pbc="F F F"
C        0.00000000       0.00000000       0.00000000
1
Properties=species:S:1:pos:R:3 config_type=isolated_atom energy=-2035.5709809589698 pbc="F F F"
O        0.00000000       0.00000000       0.00000000
1
Properties=species:S:1:pos:R:3 config_type=isolated_atom energy=-1479.0665594928669 pbc="F F F"
N        0.00000000       0.00000000       0.00000000


Thanks!

**Comment by ilyes319** [comment]
The E0s need to be computed with the same DFT as your dataset (same functional, basis set, etc). If you don't have them, use E0s="average".

**Comment by gabor1** [comment]
But we really really advise against using "average", it will lead to an unstable potential with low barriers for dissociation.

**Comment by spriti523** [comment]
Thank you so much @ilyes319 and Prof. @gabor1 . Do you think we still need to use E0s if we have already subtracted it while training, and only train with interaction energies?  And thank you for solving the posted issue earlier.

**Comment by gabor1** [comment]
In this case you should specify them exactly as 0.0 for each element.
