### ISSUE TITLE
 Release mismatch between PyPi and github

### ISSUE THREAD

**Issue by R1j1t** [ACEsuit/mace#676]
**Describe the bug**
Latest release on Github is 0.3.7 whereas PyPI has 0.3.6

**To Reproduce**
1. Compare the version numbers at https://pypi.org/project/mace-torch/#history and https://github.com/ACEsuit/mace/releases

**Expected behavior**
PyPI should be have the latest package too

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: 
 - Browser [e.g. chrome, safari]: 
 - Version [e.g. 22]: 0.3.7

**Smartphone (please complete the following information):**

**Additional context**
NA

**Comment by nihil39** [comment]
https://github.com/ACEsuit/mace/discussions/620#discussioncomment-11086310
