### ISSUE TITLE
Performace drop for systems far from the origin

### ISSUE THREAD

**Issue by Nilsgoe** [ACEsuit/mace#713]
I recognized some inconsistencies for molecules far from the coordinate origin (no pbc involved).

As a result, the calculation for the forces is roughly a factor of 2.5 times slower for these systems.

Here is a short example, but I attached a .zip with two .ipynb files which I think is better for seeing the timings:

```
import ase
from ase.build import molecule
from ase.optimize import BFGS
from ase.io import write,read
from mace.calculators import mace_off  # Ensure MACE is installed
import numpy as np
import time

# Generate anthracene Molecule
anthracene = read("anthracene.xyz") #doesn't matter which system
calculator = mace_off(model="large")
anthracene.set_calculator(calculator)

# Optimize the anthracene Geometry
optimizer = BFGS(anthracene)
optimizer.run(fmax=0.01)  


# Perform Energy and Force Calculation (Optimized Geometry)
anthracene.positions[0][0]+=1e-5  #need otherwise no new energy calc
start_time = time.time()
energy_opt = anthracene.get_potential_energy()
forces_opt = anthracene.get_forces()
end_time = time.time()
print(f"Time (optimized calculation): {end_time - start_time:.4f} seconds")

# Displace Molecule and Recalculate
displacement = np.random.uniform(49, 50, 3)  # Random displacement but very far
anthracene_displaced = anthracene.copy()
anthracene_displaced.positions += displacement

# Save displaced coordinates
write("anthracene_displaced.xyz", anthracene_displaced)

anthracene_displaced.set_calculator(calculator)

start_time = time.time()
energy_disp = anthracene_displaced.get_potential_energy()
forces_disp = anthracene_displaced.get_forces()
end_time = time.time()
print(f"Time (displaced calculation): {end_time - start_time:.4f} seconds")
```
In the notebook I always slightly displace a single atom for actually doing an energy and force calculation.
From the notebook, I get these times for displacement of [49.00687534 49.89995854 49.72021806]:
Not displaced: 35.3 ms ± 157 μs per loop (mean ± std. dev. of 10 runs, 50 loops each)
Displaced: 83.6 ms ± 3.06 ms per loop (mean ± std. dev. of 10 runs, 50 loops each)

but for a displacement of "only" [4.91370347 4.90006981 4.92243811] I get these times:
Not displaced: 35.3 ms ± 920 μs per loop (mean ± std. dev. of 10 runs, 50 loops each)
Displaced: 37.3 ms ± 4.43 ms per loop (mean ± std. dev. of 10 runs, 50 loops each)

I have no idea if it is a MACE or an ASE problem, but this behavior is not seen with the EMT calculator from ASE.
[timing_code.zip](https://github.com/user-attachments/files/17871795/timing_code.zip)

**Comment by RokasEl** [comment]
We use the matscipy neighbor list for the MACE calculator, which is faster than the ASE one but doesn't support non-periodic boxes. This requires creating a cell even for non-PBC cases.

If your molecule is far from the origin, the created cell becomes very large, slowing down neighbor list construction and causing most of the relaxation time to be spent on this step.

To mitigate this, subtract the center of mass from your positions before starting the relaxation. We plan to fix this in the future.
