### ISSUE TITLE
Allow selecting the cuda device by its ID when using cli scripts

### ISSUE THREAD

**Issue by dembart** [ACEsuit/mace#757]
**Problem**
By now, the device keyword can be 'cpu', 'cuda', 'mps', 'xpu', but one may want to choose a specific cuda device if there are multiple GPUs available. 

**Describe the solution you'd like**
Allow "cuda:ID" (e.g., "cuda:1") values of the device keyword 

**Describe alternatives you've considered**
Create run.py with```torch.cuda.set_device('cuda:1')```

**Comment**
Needs to upgrade mace/tools/arg_parser.py file

**Comment by RokasEl** [comment]
Hi, I think this would be a nice addition. In the meantime you can set the visible CUDA devices using an environment variable. E.g,

```
export CUDA_VISIBLE_DEVICES=0 # replace with the id of the gpu you want to use.
```
If only one device is visible, MACE will use that.
