### ISSUE TITLE
hard limit on the `max_ell` parameter

### ISSUE THREAD

**Issue by felixmusil** [ACEsuit/mace#8]
Hi, 

it seems that we can't use `max_ell>3` in the MACE model because of the limitation of the computations of the W3j matrix element (e3nn supports `l_max>=11`)  which is used to compute the `U_matrix_real`. Since these coefficients don't need to be computed with pytorch (no backdrop and they are computed only once), would you mind using the implementation from [sympy](https://docs.sympy.org/latest/modules/physics/wigner.html) ? 

This code will fail: 
```
model = MACE(
    r_max=10,
    num_bessel=10,
    num_polynomial_cutoff=5,
    max_ell=6,
    interaction_cls=modules.interaction_classes[
                    "RealAgnosticResidualInteractionBlock"
                ],
    interaction_cls_first=modules.interaction_classes[
                    "RealAgnosticInteractionBlock"
                ],
    num_interactions=1,
    num_elements=46,
    hidden_irreps=o3.Irreps('256x0e'),
    MLP_irreps=o3.Irreps("16x0e"),
    atomic_energies=np.zeros(46),
    avg_num_neighbors=9,
    atomic_numbers=np.arange(1,47),
    correlation=4,
    gate=torch.nn.SiLU(),
    device='cpu',
)
```

**Comment by ilyes319** [comment]
Hey [felixmusil](https://github.com/felixmusil),

Thanks for your issue. I think they are a few possible fixes to that. The easiest is putting CG for l>11 to zeros, which would also help sparsify the basis. To do this, one would need to remove the condition of line 99 in file [cg.py](https://github.com/ACEsuit/mace/blob/main/mace/tools/cg.py) to apply the filter for all correlations. We could also store more CG directly in e3nn or use sympy ones (not sure if they have the ones for real representations). 

I think the first choice is sensible, at least in the case of force fields, as a basis with such high degrees will probably not be crucial. I will do that as a first fix and then do the necessary to add real CGs either to e3nn or directly to the code.

Please note that this model is really big (correlation=4,max_ell=6). Typically, max_ell=3 gives the best results.

**Comment by felixmusil** [comment]
After tinkering a bit with the model I now realize it's clearly not a good idea to set `max_ell=6` with the MACE architecture. I wanted to test the simple 4 body correlation model (without messages) as if it was ACE which is clearly not the way to go.
